<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE foodProduction-processes [
	<!ELEMENT foodProduction-processes (process*)>
	<!ELEMENT process (description?, inputs, outputs)>
	<!ATTLIST process name CDATA #REQUIRED>
	<!ATTLIST process tech CDATA #REQUIRED>
	<!ATTLIST process skill CDATA #REQUIRED>
	<!ATTLIST process work-time CDATA #REQUIRED>
	<!ATTLIST process process-time CDATA #REQUIRED>
	<!ATTLIST process power-required CDATA #REQUIRED>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT inputs (part*, resource*)>
	<!ELEMENT outputs (part*, resource*, equipment*)>
	<!ELEMENT resource (alternative*)>
	<!ATTLIST resource name CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT alternative EMPTY>
	<!ATTLIST alternative name CDATA #REQUIRED>
	<!ATTLIST alternative amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT equipment EMPTY>
	<!ATTLIST equipment name CDATA #REQUIRED>
	<!ATTLIST equipment number CDATA #REQUIRED>
]>

<!-- List of all food production processes. -->
<foodProduction-processes>

	<!-- tech - The minimum tech level required to perform the process.  -->
	<!-- skill - The minimum person skill level in cooking to perform the process. -->
	<!-- work-time - The effort time (in millisols) required to perform the process.  Higher skilled workers will produce more effort time than lower skilled workers. -->
	<!-- process-time - The minimum time (in millisols) required for the process regardless of effort time. -->
	<!-- power-required - The total amount of power (kW hr) required for the process. -->
	<process name="Package Preserved Food"
			tech="1" skill="0"
			work-time="10"
			process-time="10"
			power-required="0.05">
		<description>Cut and freeze dry cabbage into package food.</description>

		<!-- List of inputs for the process ( parts and resources). -->
		<inputs>
			<!-- amount - The amount of the resource in kilograms. -->
			<part name="refrigerator" number="1" />
			<resource name="Cabbage" amount="3.0">
				<alternative name="Carrot" amount="5.0" />		
				<alternative name="Leaves" amount="8.0" />
				<alternative name="Swiss Chard" amount="3.0" />
				<alternative name="Potato" amount="3.0" />
			</resource>
		</inputs>

		<!-- List of outputs from the process (parts, resources, equipment). -->
		<outputs>
			<part name="refrigerator" number="1" />
			<resource name="food" amount="3.0" />
		</outputs>
	</process>

	<process name="Package Roast Peanuts into Dry Food"
		tech="0" skill="0" work-time="10" process-time="10"
			power-required="0.05">

		<description>Pack peanuts into dry food</description>

		<inputs>
			<part name="oven" number="1" />
			<resource name="Roasted Peanut" amount="5.0" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="food" amount="5.0" />
		</outputs>
	</process>


	<process name="Make Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="50"
			power-required="0.1">
		<description>Make granola bar using puffed quinoa/rice/wheat, honey/sugarcane, nuts and dried fruits.</description>
		<inputs>
			<resource name="Quinoa" amount="4.0">
				<alternative name="Rice" amount="4.0" />
				<alternative name="Wheat" amount="4.0" />
			</resource>
			<resource name="Strawberry" amount="0.5">
				<alternative name="Blueberry" amount="0.5" />
			</resource>
			<resource name="Honey"  amount="0.5">
				<alternative name="Sugarcane Juice" amount="0.5" />
			</resource>
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Granola Bar" amount="6.0" />
		</outputs>
	</process>

	<process name="Make Okara Protein Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100"
			power-required="0.1">
		<description>Make protein bars using puffed quinoa/rice/wheat, honey/sugarcane juice, nuts and dried fruits.</description>
		<inputs>
			<resource name="Quinoa" amount="2.0">
				<alternative name="Rice" amount="2.0" />
				<alternative name="Wheat" amount="2.0" />
			</resource>
			<resource name="Okara" amount="2.0" />
			<resource name="Strawberry" amount="0.5">
				<alternative name="Blueberry" amount="0.5" />
			</resource>
			<resource name="Honey" amount="0.5">
				<alternative name="Sugarcane Juice" amount="0.5" />
			</resource>
			<resource name="Peanut" amount="1.0" />
		</inputs>
		<outputs>
			<resource name="Protein Bar" amount="6.0" />
		</outputs>
	</process>
	
	<process name="Make French Fries from Potatoes"
			tech="1" skill="1"
			work-time="50"
			process-time="50"
			power-required="0.7">
		<description>Cut potatoes and make French Fries.</description>
		<inputs>
			<resource name="Potato" amount="10.0" />
			<resource name="Peanut Oil" amount="1.0">
				<alternative name="Soybean Oil" amount="1.0" />
			</resource>

		</inputs>
		<outputs>
			<resource name="French Fries" amount="10.0" />
		</outputs>
	</process>

	<process name="Make Soy Sprouts from Soybeans"
			tech="1" skill="1"
			work-time="50"
			process-time="3000"
			power-required="0.0">
		<description>Sanitize soybean seeds with sodium hypochlorite. 
			Wash the seeds and soak them in water and
			wait for germination. When germinated, freeze dry them. </description>
		<inputs>
			<part name="refrigerator" number="1" />
			<resource name="Soybean" amount="3.0" />
			<resource name="Water" amount="3.0" />
			<resource name="sodium hypochlorite" amount="0.003" />
		</inputs>

		<outputs>
			<part name="refrigerator" number="1" />
			<resource name="Soy Sprout" amount="15.0" />
		</outputs>
	</process>

	<process name="Make Quinoa Sprouts from Quinoa"
			tech="1" skill="1"
			work-time="50"
			process-time="2000"
			power-required="0.0">
		<description>Rinse the quinoa seeds in a bowl. Wash the quinoa seeds 
			to remove the soapy coating known as saponin. Soak in water and 
			drain the water after 30 minutes. Repeat the rinsing and draining 
			process every 8 hours. Put the tray of quinoa in a dark room. 
			Place the cloth back over the quinoa for protection.The quinoa will 
			sprout into a plate full of spiral-shaped roots that are at least 
			one-quarter inch in length. Dry out sprouts for up to 12 hours 
			after fully germinated. </description>
		<inputs>
			<resource name="Quinoa" amount="3.0" />
			<resource name="Water" amount="3.0" />
		</inputs>

		<outputs>
			<resource name="Quinoa Sprout" amount="15.0" />
		</outputs>
	</process>

	<!-- see http://dx.doi.org/10.2135/cropsci1999.0011183X0039000200017x and http://dx.doi.org/10.1016/B978-0-12-394437-5.00130-3 for soymilk/tofu yield (5.1 ml/g and 0.865 g/ml) and okara yield (1.1 per kg beans) and water:dry bean ratio (8:1 to 10:1); assumes density of soymilk is 1.03 kg/l and about 3/4 as much sugar as before; aiming for 13.6 g/l total sugar -->
	<process name="Make Okara and Soymilk from Soybeans"
		tech="1" skill="0" work-time="30" process-time="70"
			power-required="0.5">

		<description> Make pulp (Okara) and Soymilk from Soybean after
			Washing, Dehulling, Soaking, Milling, Paste
			Heating, and Filtration. </description>
		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="0.95" />
			<resource name="Water" amount="10.5" />
			<resource name="Sugar" amount="0.0465" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Grey Water" amount="1.9" />
			<resource name="Okara" amount="1.045" />
			<resource name="Soymilk" amount="5" />
		</outputs>
	</process>

	<process name="Make Sesame Milk from Soymilk"
		tech="1" skill="1" work-time="20" process-time="20"
			power-required="1.0">

		<description> Make sesame milk from soymilk </description>
		<inputs>
			<part name="blender" number="1" />
			<resource name="sesame seed" amount="0.5" />
			<resource name="soymilk" amount="4.5" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<resource name="sesame milk" amount="5.0" />
		</outputs>
	</process>
	
	<process name="Press and Refine Peanut Oil from Peanuts"
		tech="2" skill="1" work-time="50" process-time="400"
			power-required="2.0">

		<description>Derive vegetableâ€…oil from peanuts. Press and refine it
			for use </description>

		<inputs>
			<resource name="Peanut" amount="4.0" />
		</inputs>
		<outputs>
			<resource name="Peanut Oil" amount="2.0" />
		</outputs>
	</process>

	<process name="Chop and Roast Peanuts in Oven"
		tech="1" skill="1" work-time="50" process-time="300"
			power-required="1.0">

		<description>Chopped up peanuts and roast them in oven </description>

		<inputs>
			<part name="oven" number="1" />
			<resource name="Peanut" amount="5.0" />
			<resource name="table salt" amount="0.5" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="Roasted Peanut" amount="5.0" />
		</outputs>
	</process>

	<process name="Make Peanut Butter from Peanuts"
		tech="1" skill="0" work-time="50" process-time="50"
			power-required="0.2">

		<description>Ground peanuts, mix with oil, pour the mixture into food processor.
		Blend until smooth.</description>

		<inputs>
			<part name="blender" number="1" />
			<!--
			TODO: add cocoa powder, cinnamon or other spice
			/>-->
			<resource name="Peanut" amount="3.0" />
			<resource name="Soybean Oil" amount="0.5" />
			<resource name="table salt" amount="0.1" />
			<resource name="Soy Protein" amount="0.1" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<resource name="Peanut Butter" amount="3.5" />
		</outputs>
	</process>
	
	<process name="Bake White Bread from Soy Flour"
		tech="1" skill="1" work-time="50" process-time="200"
			power-required="1.0">

		<description> Make 2 loaves of White Bread from Soy Flour </description>

		<inputs>
			<part name="oven" number="1" />
			<resource name="Soy Flour" amount="1.0" />
			<resource name="Water" amount="0.33" />
			<resource name="Yeast" amount="0.01" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="White Bread" amount="1.2" />
		</outputs>
	</process>

	<process name="Make Tofu from Soymilk and Calcium Sulfate"
		tech="1" skill="1" work-time="25" process-time="50"
			power-required="1.0">

		<description> Boil up soymilk, add calcium sulfate as coagulant,
			gently stir and heat, and the curds will separate.</description>

		<inputs>
			<part name="stove" number="1" />
			<resource name="Soymilk" amount="2.5" />
			<resource name="calcium sulfate" amount="0.03" />
		</inputs>
		<outputs>
			<part name="stove" number="1" />
			<resource name="Tofu" amount="2.1" />
			<!-- Grey Water is (edible) tofu whey -->
			<resource name="Grey Water" amount="0.4" />
		</outputs>
	</process>
	
	<process name="Make Tofu from Soymilk and Epsom Salt"
		tech="1" skill="1" work-time="25" process-time="50"
			power-required="1.0">

		<description> Boil up Soymilk, add Epsom Salt as Coagulant,
			gently stir and heat, and the curds will separate.</description>

		<inputs>
			<part name="stove" number="1" />
			<resource name="Soymilk" amount="2.5" />
			<resource name="Epsom Salt" amount="0.021" />
		</inputs>
		<outputs>
			<part name="stove" number="1" />
			<resource name="Tofu" amount="2.1" />
			<!-- Grey Water is (edible) tofu whey -->
			<resource name="Grey Water" amount="0.4" />
		</outputs>
	</process>

	<process name="Make Tofu from Soymilk and Vinegar"
		tech="1" skill="1" work-time="25" process-time="50"
			power-required="1.0">

		<description> Boil up Soymilk, add Epsom Salt as Coagulant,
			gently stir and heat, and the curds will separate.</description>

		<inputs>
			<part name="stove" number="1" />
			<resource name="Soymilk" amount="2.5" />
			<resource name="Rice Vinegar" amount="0.039" />
		</inputs>
		<outputs>
			<part name="stove" number="1" />
			<resource name="Tofu" amount="2.1" />
			<!-- Grey Water is (edible) tofu whey -->
			<resource name="Grey Water" amount="0.4" />
		</outputs>
	</process>

	<process name="Make Tofu from Soybeans, Water, and Epsom Salt (large batch)"
		tech="1" skill="2" work-time="70" process-time="400"
			power-required="3.8">

		<description> Boil up Soybeans, grind into soymilk, filter off okra, and add Epsom Salt as Coagulants.
			gently stir and heat, the curds will separate.</description>

		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="1.7" />
			<resource name="Water" amount="18.7" />
			<resource name="Epsom Salt" amount="0.076" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="7.5" />
			<resource name="Okara" amount="1.87" />
			<resource name="Grey Water" amount="3.4" />
		</outputs>
	</process>

	<process name="Make Tofu from Soybeans, Water, and Vinegar (large batch)"
		tech="1" skill="2" work-time="70" process-time="400"
			power-required="3.8">

		<description> Boil up Soybeans, grind into soymilk, filter off okra, and add vinegar as Coagulants.
			gently stir and heat, the curds will separate.</description>

		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="1.7" />
			<resource name="Water" amount="18.7" />
			<resource name="Rice Vinegar" amount="0.0691" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="7.5" />
			<resource name="Okara" amount="1.87" />
			<resource name="Grey Water" amount="3.4" />
		</outputs>
	</process>

	<process name="Make Soymilk and Tofu from Soybeans, Water, and Epsom Salt"
		tech="1" skill="2" work-time="53" process-time="400"
			power-required="2.8">

		<description> Boil up Soybeans, grind into soymilk, filter off okra, and add Epsom Salt as Coagulants.
			gently stir and heat, the curds will separate. Save and sweeten some soymilk.</description>

		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="1.25" />
			<resource name="Water" amount="13.75" />
			<resource name="Epsom Salt" amount="0.556" />
			<resource name="Sugar" amount="0.280" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="3.0" />
			<resource name="Soymilk" amount="3.0" />
			<resource name="Okara" amount="1.375" />
			<resource name="Grey Water" amount="6.07" />
		</outputs>
	</process>

	<process name="Make Soymilk and Tofu from Soybeans, Water, and Vinegar"
		tech="1" skill="2" work-time="53" process-time="400"
			power-required="2.8">

		<description> Boil up Soybeans, grind into soymilk, filter off okra, and add vinegar as coagulants.
			gently stir and heat, the curds will separate. Save and sweeten some soymilk.</description>

		<inputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Soybean" amount="1.25" />
			<resource name="Water" amount="13.75" />
			<resource name="Rice Vinegar" amount="0.0508" />
			<resource name="Sugar" amount="0.280" />
		</inputs>
		<outputs>
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="3.0" />
			<resource name="Soymilk" amount="3.0" />
			<resource name="Okara" amount="1.375" />
			<resource name="Grey Water" amount="6.07" />
		</outputs>
	</process>

	<process name="Process Soybean into Soy Flour"
		tech="1" skill="2" work-time="50" process-time="300"
			power-required="0.25">
		<description> Create defatted soy flour by cracking, screening, heating soybean 
		at 130 deg C with hot extrusion and high pressure .  </description>
		<inputs>
			<part name="oven" number="1" />
			<resource name="Soybean" amount="1.0" />
			<resource name="Water" amount="1.0" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="Soy Flour" amount="1.0" />
		</outputs>
	</process>

	<!-- https://www.youtube.com/watch?v=LGMVoL7nGSI says 30 g vinegar per 500 g cooked substrate... https://en.wikipedia.org/wiki/Tempeh#Dry_matter_losses_and_yield suggests 1.9 kg tempeh from 1 kg raw soybeans 1 kg dry ~2.3 kg cooked http://dx.doi.org/10.1016/B978-0-12-394437-5.00130-3 for moisture content, and https://www.youtube.com/watch?v=Zfkd6VXT9_0 for starter -->
	<process name="Make Tempeh from Soybeans"
		tech="1" skill="2" work-time="70" process-time="1000"
			power-required="0.6">

		<description> Boil Soybeans, add vinegar and Rhizopus oligosporus starter, and
			allow to ferment.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.0" />
			<resource name="Water" amount="3.5" />
			<resource name="Rice Vinegar" amount="0.138" />
			<resource name="Rhizopus oligosporus" amount="0.0023" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<resource name="Tempeh" amount="1.9" />
			<resource name="Grey Water" amount="2.0" />
		</outputs>
	</process>

	<!-- Tempeh yield from okara is approximate/estimated, assuming excess water from okara evaporates away -->
	<process name="Make Black Oncom from Okara"
		tech="1" skill="2" work-time="71" process-time="10500"
			power-required="0.1">

		<description> Moisten Okara with vinegar, add Rhizopus oligosporus starter, and
			allow to ferment.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="Rice Vinegar" amount="0.174" />
			<resource name="Okara" amount="2.9" />
			<resource name="Rhizopus oligosporus" amount="0.0029" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<resource name="Tempeh" amount="2.2" />
		</outputs>
	</process>
	
	<process name="Make Tempeh from half Soybeans and half Okara"
		tech="1" skill="2" work-time="72" process-time="1000"
			power-required="0.63">

		<description> Boil Soybeans, add vinegar, Rhizopus oligosporus starter, and okara,
			and allow to ferment.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.0" />
			<resource name="Water" amount="3.5" />
			<resource name="Rice Vinegar" amount="0.198" />
			<resource name="Okara" amount="1.0" />
			<resource name="Rhizopus oligosporus" amount="0.0033" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<resource name="Tempeh" amount="2.66" />
			<resource name="Grey Water" amount="1.0" />
		</outputs>
	</process>
	
	<process name="Make Tofu and Tempeh from Soybeans and Vinegar (large batch)"
		tech="1" skill="2" work-time="125" process-time="1000"
			power-required="3.85">

		<description> Boil Soybeans, blend, separate okara and ferment with Rhizopus
			oligosporus starter. Add vinegar to soymilk as coagulant. This uses
			all the okara by-product of tofu.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.7" />
			<resource name="Water" amount="18.7" />
			<resource name="Rice Vinegar" amount="0.181" />
			<resource name="Rhizopus oligosporus" amount="0.0019" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="7.5" />
			<resource name="Tempeh" amount="1.42" />
			<resource name="Grey Water" amount="4.83" />
		</outputs>
	</process>
	
	<process name="Make Tofu and Tempeh from Soybeans and Epsom Salt (large batch)"
		tech="1" skill="2" work-time="125" process-time="1000"
			power-required="3.85">

		<description> Boil Soybeans, blend, separate okara and ferment with Rhizopus
			oligosporus starter. Add vinegar to soymilk as coagulant. This uses
			all the okara by-product of tofu.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.7" />
			<resource name="Water" amount="18.7" />
			<resource name="Rice Vinegar" amount="0.112" />
			<resource name="Rhizopus oligosporus" amount="0.0019" />
			<resource name="Epsom Salt" amount="0.0962" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="7.5" />
			<resource name="Tempeh" amount="1.42" />
			<resource name="Grey Water" amount="4.83" />
		</outputs>
	</process>
	
	<process name="Make Tofu, Soymilk, and Tempeh from Soybeans and Vinegar"
		tech="1" skill="2" work-time="125" process-time="1000"
			power-required="1.3">

		<description> Boil Soybeans, blend, separate okara and ferment with Rhizopus
			oligosporus starter. Add vinegar to some soymilk as coagulant,
			sweetening the remainder.</description>

		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.25" />
			<resource name="Water" amount="13.75" />
			<resource name="Rice Vinegar" amount="0.133" />
			<resource name="Rhizopus oligosporus" amount="0.0014" />
			<resource name="Sugar" amount="0.028" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="3.0" />
			<resource name="Soymilk" amount="3.0" />
			<resource name="Tempeh" amount="1.04" />
			<resource name="Grey Water" amount="6.07" />
		</outputs>
	</process>
	
	<process name="Make Tofu, Soymilk, and Tempeh from Soybeans and Epsom Salt"
		tech="1" skill="2" work-time="125" process-time="1000"
			power-required="1.3">

		<description>Boil Soybeans, blend, separate okara and ferment with Rhizopus
			oligosporus starter. Add vinegar to some soymilk as coagulant,
			sweetening the remainder.</description>
		
		<inputs>
			<part name="autoclave" number="1" />
			<resource name="soybean" amount="1.25" />
			<resource name="Water" amount="13.75" />
			<resource name="Rice Vinegar" amount="0.0825" />
			<resource name="Rhizopus oligosporus" amount="0.0014" />
			<resource name="Epsom Salt" amount="0.0707" />
			<resource name="Sugar" amount="0.028" />
		</inputs>
		<outputs>
			<part name="autoclave" number="1" />
			<part name="blender" number="1" />
			<part name="stove" number="1" />
			<resource name="Tofu" amount="3.0" />
			<resource name="Soymilk" amount="3.0" />
			<resource name="Tempeh" amount="1.04" />
			<resource name="Grey Water" amount="6.07" />
		</outputs>
	</process>
	
	<process name="Process White Rice into Rice Flour"
		tech="1" skill="2" work-time="25" process-time="300"
			power-required="0.25">
		<description> Rinse rice, dry, and finely grind.</description>
		<inputs>
			<resource name="White Rice" amount="1.0" />
			<resource name="Water" amount="3.0" />
			<resource name="calcium sulfate" amount="0.05" />
		</inputs>
		<outputs>
			<resource name="Water" amount="2.9" />
			<resource name="Rice Flour" amount="1.0" />
		</outputs>

	</process>

	<process name="Process Rice into White Rice and rice bran oil"
		tech="1" skill="1" work-time="50" process-time="100" power-required="0.5">
		<description> Remove hulls, bran layers and germ from rice.
		May enrich milled rice with vitamins and minerals </description>

		<inputs>
			<resource name="Rice" amount="2.0" />

		</inputs>
		<outputs>
			<resource name="White Rice" amount="1.33" />
			<resource name="Crop Waste" amount="0.495" />
			<resource name="rice bran oil" amount="0.175" />			
		</outputs>
	</process>

	<!-- http://www.knowledgebank.irri.org/step-by-step-production/postharvest/milling says rice is 20 % hull, 11 % bran, and 69 % other ideally, but ranges are 20 % hull, 8-12 % bran, and 68-72 % other; extrapolates waste from buckwheat -->
	<process name="Process Rice into Brown Rice"
		tech="1" skill="0" work-time="50" process-time="50" power-required=".1">
		<description> Remove only hulls from rice. The light brown color is due to the presence of the bran layers
		and the embryo or germ. Brown rice requires longer cooking time than either parboiled or regular-milled white rice </description>

		<inputs>
			<resource name="Rice" amount="2.0" />

		</inputs>
		<outputs>
			<resource name="Brown Rice" amount="1.55" />
			<resource name="Crop Waste" amount="0.45" />				
		</outputs>
	</process>

	<!-- http://www.knowledgebank.irri.org/step-by-step-production/postharvest/milling says rice is 20 % hull, 11 % bran, and 69 % other ideally, but ranges are 20 % hull, 8-12 % bran, and 68-72 % other; extrapolates waste from buckwheat -->
	<process name= "Process Brown Rice into Rice Flour"
		tech="1" skill="2" work-time="38" process-time="330"
			power-required="5.3">
		<description> Rinse rice, dry, and finely grind </description>
		<inputs>
			<resource name="Brown Rice" amount="1.0" />
			<resource name="Water" amount="3.0" />

		</inputs>
		<outputs>
			<resource name="Grey Water" amount="2.9" />
			<resource name="Rice Flour" amount="0.856" />
			<resource name="rice bran oil" amount="0.112" />
			<resource name="Food Waste" amount="0.032" />
		</outputs>
	</process>
		
	<process name="Process Brown Rice into White Rice"
		tech="1" skill="2" work-time="15" process-time="30" power-required="0.3">
		<description> Remove bran layers and germ from rice.
		May enrich milled rice with vitamins and minerals </description>

		<inputs>
			<resource name="Brown Rice" amount="2.0" />

		</inputs>
		<outputs>
			<resource name="White Rice" amount="1.71" />
			<resource name="rice bran oil" amount="0.225" />
			<resource name="Crop Waste" amount="0.064" />				
		</outputs>
	</process>
	
	<!-- https://umanitoba.ca/faculties/engineering/departments/ce2p2e/alternative_village/media/19_Physical_Chemical_surface_properties_wheat_husk_rye_husk_soft_wood_Bledzki.pdf 
	    says 15-20 % husk for wheat; 
	    https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/milling-fractions says for Buckwheat cultivar Siva, 
	    it is 55.4 % flour (from raw grain), 24.2 % bran, and 17.4 % husk according to Skrabanja et al., 2003a 
	    assumes waste is linear from grain to wholegrain to white   -->
	<process name= "Process Wheat into Wheat Flour"
		tech="1" skill="2" work-time="50" process-time="400"
			power-required="5.0">
		<description> Rinse wheat, dry, and finely grind </description>
		<inputs>
			<resource name="Wheat" amount="1.0" />
			<resource name="Water" amount="3.0" />

		</inputs>
		<outputs>
			<resource name="Grey Water" amount="2.9" />
			<resource name="Wheat Flour" amount="0.792" />
			<resource name="Crop Waste" amount="0.208" />
		</outputs>
	</process>
		
	<process name="Extract Soy Protein from Soy Flour"
		tech="2" skill="2" work-time="50" process-time="400"
			power-required="1.0">
		<description> Create Defatted Soy Proteins from Soy Flour by Alkaline extraction, Centrifugation, Acid Precipitation of Proteins, Centrifugation, Washing,  Spry Drying and Isolation of Proteins   </description>
		<inputs>
			<resource name="Soy Flour" amount="1.0" />
			<resource name="Water" amount="3.0" />
		</inputs>
		<outputs>
			<resource name="Soy Protein" amount="1.0" />
		</outputs>
	</process>

	<!-- https://soybeanresearchinfo.com/research-highlight/increasing-soybean-oil-yield-through-targeted-gene-silencing-and-over-expression/ says 16-22 % oil once all water is removed; using 19 % -->
	<process name="Expel Soybean Oil from Soybean"
		tech="1" skill="0" work-time="50" process-time="100"
			power-required=".5">
		<description> Cracking, Screening, Heating at 130 deg C, Hot extrusion, Pressure at 40-60 MPa. Screening and Decantation of Oil </description>
		<inputs>
			<part name="oven" number="1" />
			<resource name="Soybean" amount="2.5" />
		</inputs>
		<outputs>
			<part name="oven" number="1" />
			<resource name="Soybean Oil" amount="0.437" />
			<resource name="Food Waste" amount="2.063" />
			<!-- It should be press cake (and maybe some grey water that is squeezed out too?), which can be used like okara if cooked? <resource name="Okara" amount="2.063"/> -->
		</outputs>
	</process>

	<!-- DOI 10.17485/ijst/2016/v9i30/89371 tells growth and oil yield; 50 % from crops.xml is well within the range -->
	<process name="Press Sesame Oil from Sesame Seeds"
		tech="1" skill="0" work-time="50" process-time="100"
			power-required=".5">
		<description> Continuous pressing by means of expellers is a widely applied process for the extraction of oil from sesame seeds</description>
		<inputs>
			<resource name="Sesame Seed" amount="2.5" />
		</inputs>
		<outputs>
			<resource name="Sesame Oil" amount="1.25" />
			<resource name="Food Waste" amount="1.25" />
		</outputs>
	</process>

	<!-- https://en.wikipedia.org/wiki/Garlic_oil#Preparation says 1 gram pure oil requres 500 grams garlic, and that it is 900 times as strong as fresh garlic and 200 times as strong as dry garlic -->
	<process name="Press Garlic Oil from Garlic"
		tech="1" skill="0" work-time="50" process-time="50"
			power-required=".5">
		<description> Continuous pressing by means of expellers is a widely applied
						process for the extraction of oil from Garlic</description>
		<inputs>
			<resource name="Garlic" amount="5.0" />
			<!-- 0.99 oil means 2x as strong as dry garlic; 0.39 means 5x as strong -->
			<resource name="Sesame Oil" amount="0.99" />
		</inputs>
		<outputs>
			<resource name="Garlic Oil" amount="1.0" />
			<resource name="Food Waste" amount="4.99" />
		</outputs>
	</process>

	<process name="Press Olive Oil from Olive"
		tech="1" skill="0" work-time="50" process-time="50"
			power-required=".5">
		<description>Ripe olives can yield up to 30% of oil. It's about 
			3 kg of olives per liter (around 0.9kg) of oil.
		</description>
		<inputs>
			<resource name="Olive" amount="3.0" />
			<resource name="Water" amount="0.9" />
		</inputs>
		<outputs>
			<resource name="Olive Oil" amount="0.9" />
			<resource name="Food Waste" amount="3.0" />
		</outputs>
	</process>
	
	<process name="Make Veggie Patty from Veg, Tofu and Spice"