<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE governance [
	<!ELEMENT governance (agendas, authorities)>

	<!ELEMENT agendas (agenda+)>
	<!ELEMENT agenda (capability+)>
	<!ATTLIST agenda name CDATA #REQUIRED>
	<!ATTLIST agenda objective CDATA #REQUIRED>
	<!ATTLIST agenda findings CDATA #REQUIRED>
	<!ATTLIST agenda data CDATA #REQUIRED>
	<!ELEMENT capability (preference*)>
	<!ATTLIST capability description CDATA #REQUIRED>
	<!ELEMENT preference EMPTY>
	<!ATTLIST preference type CDATA #REQUIRED>
	<!ATTLIST preference name CDATA #REQUIRED>
	<!ATTLIST preference modifier CDATA #REQUIRED>

	<!ELEMENT authorities (authority+)>
	<!ELEMENT authority (country+, settlement-name*, rover-name*)>
	<!ATTLIST authority code CDATA #REQUIRED>
	<!ATTLIST authority name CDATA #REQUIRED>
	<!ATTLIST authority corporation (true|false) #REQUIRED>
	<!ATTLIST authority agenda CDATA #REQUIRED>
	<!ATTLIST authority gender-ratio CDATA #REQUIRED>
	<!ELEMENT country EMPTY>
	<!ATTLIST country name CDATA #REQUIRED>
	<!ELEMENT settlement-name EMPTY>
	<!ATTLIST settlement-name name CDATA #REQUIRED>
	<!ELEMENT rover-name EMPTY>
	<!ATTLIST rover-name name CDATA #REQUIRED>
]>

<governance>
	<!-- Mission agendas that can be used by authorities -->
	<agendas>
		<agenda name="Areological Science"
				objective="Formalize methodologies and disciplines in studying Mars's environment"
				findings="Collect evidence of proposed organic process for the origin and evolution of the planet"
				data="Characterize the morphology and features of local landforms as a part of the global system">
			<capability description="Catalogue mineral volatiles due to volcanic outpurings, impacts, and crustsal fracturing">
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.6"/>
				<preference type="MISSION" name="AREOLOGY" modifier="1.4"/>
				<preference type="MISSION" name="METEOROLOGY" modifier="1.3"/>
				<preference type="SCIENCE" name="CHEMISTRY" modifier="5"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="2"/>
			</capability>
			<capability description="Investigate how terrain features relate to seismic activities">
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.4"/>
				<preference type="MISSION" name="MINING" modifier="1.2"/>
				<preference type="SCIENCE" name="AREOLOGY" modifier="9"/>
				<preference type="SCIENCE" name="CHEMISTRY" modifier="4"/>				
			</capability>
			<capability description="Design a multi-sensor network for time-series observation and data analysis">
				<preference type="MISSION" name="EXPLORATION" modifier="1.4"/>
				<preference type="MISSION" name="DELIVERY" modifier="0.7"/>
				<preference type="MISSION" name="TRADE" modifier="0.7"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.1"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="8"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="8"/>
			</capability>
		</agenda>
		
		<agenda name="Colony Construction"
				objective="Build self-sustaining colonies"
				findings="Understand implications and best practices in mass resource utilization and distribution"
				data="Study Marsquakes on erected structures and environment">
			<capability description="Study meteorological environmental factors">
				<preference type="MISSION" name="AREOLOGY" modifier="1.4"/>
				<preference type="MISSION" name="METEOROLOGY" modifier="1.6"/>
				<preference type="SCIENCE" name="AREOLOGY" modifier="2"/>
				<preference type="SCIENCE" name="METEOROLOGY" modifier="9"/>
			</capability>
			<capability description="Fortify building structural integrity">
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.3"/>
				<preference type="MISSION" name="MINING" modifier="1.2"/>
				<preference type="SCIENCE" name="AREOLOGY" modifier="2"/>
				<preference type="SCIENCE" name="MATHEMATICS" modifier="2"/>	
				<preference type="SCIENCE" name="ENGINEERING" modifier="5"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="5"/>											
			</capability>
			<capability description="Refine techniques for ISRU polymer synthesis">
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.9"/>
				<preference type="MISSION" name="MINING" modifier="3"/>
				<preference type="SCIENCE" name="AREOLOGY" modifier="2"/>
			</capability>
		</agenda>
		
		<agenda name="Finding Life"
				objective="Answer the question of life past and present on Mars"
				findings="Look for signature of life in soil data"
				data="Analyze and Cataloging data from various sites">
			<capability description="Follow the water">
				<preference type="MISSION" name="BIOLOGY" modifier="1.9"/>
				<preference type="SCIENCE" name="BOTANY" modifier="3"/>				
				<preference type="MISSION" name="COLLECT_ICE" modifier="1.2"/>
				<preference type="SCIENCE" name="BIOLOGY" modifier="4"/>	
				<preference type="SCIENCE" name="CHEMISTRY" modifier="7"/>								
			</capability>
			<capability description="Search regions capable hosting/sustaining microbial life">
				<preference type="MISSION" name="BIOLOGY" modifier="1.6"/>			
				<preference type="SCIENCE" name="BIOLOGY" modifier="6"/>
				<preference type="SCIENCE" name="BOTANY" modifier="6"/>				
				<preference type="SCIENCE" name="CHEMISTRY" modifier="6"/>				
			</capability>
			<capability description="Analyze bio-signatures in rocks and mineral ice">
				<preference type="MISSION" name="BIOLOGY" modifier="1.8"/>
				<preference type="MISSION" name="COLLECT_ICE" modifier="1.4"/>
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.3"/>
				<preference type="MISSION" name="MINING" modifier="2"/>
				<preference type="SCIENCE" name="CHEMISTRY" modifier="7"/>				
			</capability>
			<capability description="Core drill rock data from selected locations">
				<preference type="MISSION" name="EXPLORATION" modifier="1.8"/>
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.4"/>
				<preference type="MISSION" name="MINING" modifier="1.6"/>	
				<preference type="SCIENCE" name="CHEMISTRY" modifier="7"/>	
			</capability>
		</agenda>
		
		<agenda name="Health Hazards"
				objective="Research short and long term medical impact on human health"
				findings="Identify on the various health hazards for human beings living on Mars"
				data="Classify environmental hazards for surface operation">
			<capability description="Investigate biological hazards">
				<preference type="MISSION" name="BIOLOGY" modifier="1.6"/>
				<preference type="MISSION" name="COLLECT_ICE" modifier="1.2"/>
				<preference type="MISSION" name="METEOROLOGY" modifier="1.4"/>
				<preference type="SCIENCE" name="BIOLOGY" modifier="7"/>
				<preference type="SCIENCE" name="BOTANY" modifier="5"/>				
				<preference type="SCIENCE" name="MEDICINE" modifier="6"/>				
			</capability>
			<capability description="Examining microbes in water ice">
				<preference type="MISSION" name="BIOLOGY" modifier="1.4"/>
				<preference type="MISSION" name="COLLECT_ICE" modifier="2"/>
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.2"/>
				<preference type="MISSION" name="MINING" modifier="1"/>
				<preference type="SCIENCE" name="BIOLOGY" modifier="6"/>
				<preference type="SCIENCE" name="BOTANY" modifier="3"/>								
			</capability>
			<capability description="Observe radiation risks, limits and exposures">
				<preference type="MISSION" name="AREOLOGY" modifier="1.8"/>
				<preference type="MISSION" name="BIOLOGY" modifier="1.2"/>
				<preference type="MISSION" name="COLLECT_ICE" modifier="1.1"/>
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.1"/>
				<preference type="SCIENCE" name="MEDICINE" modifier="9"/>
			</capability>
		</agenda>
		
		<agenda name="Human Habitation"
				objective="Characterize and determining factors contributing to human habitability"
				findings="Identify engineering challenge in constructing surface, underground and cliff-side dwelling"
				data="Analyze atmospheric conditions and geographical factors of human habitability in a local region">
			<capability description="Predict meteorological changes">
				<preference type="MISSION" name="AREOLOGY" modifier="1.5"/>
				<preference type="MISSION" name="METEOROLOGY" modifier="2"/>
				<preference type="SCIENCE" name="METEOROLOGY" modifier="1"/>
			</capability>
			<capability description="Study underground water reserve">
				<preference type="MISSION" name="COLLECT_ICE" modifier="1.9"/>
				<preference type="MISSION" name="AREOLOGY" modifier="1.6"/>	
				<preference type="SCIENCE" name="CHEMISTRY" modifier="7"/>							
			</capability>
			<capability description="Characterize radiation countermeasures">
				<preference type="MISSION" name="BIOLOGY" modifier="1.8"/>
				<preference type="MISSION" name="METEOROLOGY" modifier="1.3"/>
				<preference type="SCIENCE" name="MEDICINE" modifier="5"/>
			</capability>
		</agenda>
		
		<agenda name="Planet Life"
				objective="Make life multiplanetary"
				findings="Survey sociological and ideological implications in populating a region"
				data="Unlock factors for transforming Mars into hospitable biomes to usher in human colonization">
			<capability description="Conceptualize interplanetary transportation network">
				<preference type="MISSION" name="DELIVERY" modifier="1.9"/>
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="TRADE" modifier="2"/>
				<preference type="MISSION" name="RESCUE_SALVAGE_VEHICLE" modifier="4"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.2"/>
			</capability>
			<capability description="Study terraforming Mars environment">
				<preference type="MISSION" name="AREOLOGY" modifier="1.3"/>
				<preference type="MISSION" name="BIOLOGY" modifier="1.3"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.3"/>
				<preference type="SCIENCE" name="CHEMISTRY" modifier="3"/>
				<preference type="SCIENCE" name="AREOLOGY" modifier="7"/>				
			</capability>
			<capability description="Investigate environmentally sustainable energy solutions">
				<preference type="MISSION" name="AREOLOGY" modifier="1.2"/>
				<preference type="MISSION" name="DELIVERY" modifier="1.2"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="6"/>				
			</capability>
			<capability description="Improve vehicle range and performance">
				<preference type="MISSION" name="EXPLORATION" modifier="0.8"/>
				<preference type="MISSION" name="RESCUE_SALVAGE_VEHICLE" modifier="1.6"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.3"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="5"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="2"/>
			</capability>			
		</agenda>
		
		<agenda name="Mineral Prospecting"
				objective="Prospect mineral deposits and evaluate mineral compositions"
				findings="Document the process and history of climate on Mars"
				data="Analyze the wealth of mineral contents from the colleted soil data">
			<capability description="Analyze various signatures of minerals">
				<preference type="MISSION" name="AREOLOGY" modifier="1.3"/>
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.3"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.8"/>
				<preference type="MISSION" name="MINING" modifier="1.3"/>
				<preference type="SCIENCE" name="CHEMISTRY" modifier="8"/>
			</capability>
			<capability description="Corroborate surface geological data with on-orbit scans">
				<preference type="MISSION" name="AREOLOGY" modifier="1.5"/>
				<preference type="SCIENCE" name="AREOLOGY" modifier="7"/>	
				<preference type="SCIENCE" name="ASTRONOMY" modifier="4"/>								
			</capability>
			<capability description="Analyze meteorite fragments">
				<preference type="MISSION" name="EXPLORATION" modifier="1.4"/>			
				<preference type="SCIENCE" name="PHYSICS" modifier="3"/>		
			</capability>					
			<capability description="Core drill rock data from selected locations">
				<preference type="MISSION" name="EXPLORATION" modifier="1.9"/>
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.4"/>
				<preference type="MISSION" name="MINING" modifier="2"/>	
				<preference type="SCIENCE" name="CHEMISTRY" modifier="7"/>						
			</capability>
		</agenda>

		<agenda name="Communication Network"
				objective="Develop proven construction methods for erecting terrestrial-based communication stations"
				findings="Identify components and computational tools critical for technological breakthrough"
				data="Analyze gravity and atmospheric variability for deploying laser communication array">
			<capability description="Identify methods for safeguarding and securing surface communication equipments"> 
				<preference type="MISSION" name="EXPLORATION" modifier="1.4"/>			
				<preference type="SCIENCE" name="PHYSICS" modifier="6"/>				
				<preference type="SCIENCE" name="ENGINEERING" modifier="8"/>				
				<preference type="SCIENCE" name="MATHEMATICS" modifier="3"/>				
			</capability>
			<capability description="Assess environmental suitability for communication network">
				<preference type="MISSION" name="AREOLOGY" modifier="1.3"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.3"/>
				<preference type="SCIENCE" name="METEOROLOGY" modifier="6"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="3"/>				
			</capability>
			<capability description="Analyze the weather impact">
				<preference type="MISSION" name="METEOROLOGY" modifier="1.8"/>
				<preference type="MISSION" name="COLLECT_ICE" modifier="1.4"/>
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.3"/>
				<preference type="MISSION" name="MINING" modifier="2"/>
				<preference type="SCIENCE" name="CHEMISTRY" modifier="7"/>				
			</capability>
		</agenda>
				
		<agenda name="Space Testing and Integration"
				objective="Characterize environmental protocols for rigorous experimentation and testing"
				findings="Determine human factors and  for setting up restricted and quarantine zones"
				data="Characterize the morphology of this local region as test bed for developing advanced technologies of interest">
			<capability description="Develop techniques for automation for testing and experimentation">
				<preference type="SCIENCE" name="ENGINEERING" modifier="3"/>
				<preference type="SCIENCE" name="COMPUTING" modifier="3"/>				
				<preference type="SCIENCE" name="PHYSICS" modifier="3"/>
			</capability>
			<capability description="Survey sites for environmental suitability for various projects">
				<preference type="MISSION" name="AREOLOGY" modifier="1.3"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.3"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="5"/>
				<preference type="SCIENCE" name="MEDICINE" modifier="5"/>				
			</capability>
			<capability description="Identify methods of hazard wastes management">
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="4"/>
				<preference type="SCIENCE" name="MEDICINE" modifier="5"/>	
				<preference type="SCIENCE" name="BIOLOGY" modifier="5"/>						
			</capability>
			<capability description="Integrate hardware equipment and computational tools">
				<preference type="MISSION" name="TRADING" modifier="1.1"/>
				<preference type="SCIENCE" name="COMPUTING" modifier="7"/>				
				<preference type="SCIENCE" name="PHYSICS" modifier="7"/>				
				<preference type="SCIENCE" name="MATHEMATICS" modifier="7"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="7"/>
			</capability>
		</agenda>
		
		<agenda name="Settling Mars"
				objective="Make Mars the second home for humanity"
				findings="Investigate local in-situ resources that one can collect and process for immediate uses"
				data="Analyze structural integrity of geological features for building settlements in this region">
			<capability description="Engineer soil capable of hosting and sustaining organic microbial life">
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.3"/>
				<preference type="SCIENCE" name="BIOLOGY" modifier="6"/>		
				<preference type="SCIENCE" name="BOTANY" modifier="6"/>	
				<preference type="TASK" name="TendGreenhouse" modifier="1.2"/>							
			</capability>
			<capability description="Improve building structural integrity">
				<preference type="SCIENCE" name="ENGINEERING" modifier="8"/>
				<preference type="SCIENCE" name="COMPUTING" modifier="3"/>	
				<preference type="SCIENCE" name="PHYSICS" modifier="6"/>														
			</capability>
			<capability description="Minimize physiological effects of long term exposure to martian environment">
				<preference type="MISSION" name="AREOLOGY" modifier="1"/>
				<preference type="MISSION" name="BIOLOGY" modifier="1.5"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.2"/>
				<preference type="MISSION" name="METEOROLOGY" modifier="1.2"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="5"/>
				<preference type="SCIENCE" name="MEDICINE" modifier="8"/>
			</capability>
		</agenda>
		
		<agenda name="Space Research"
				objective="Leapfrog scientific knowledge and technological pursuit"
				findings="Develop framework for applied space research in this frontier"
				data="Analyze various region impact how space research is conducted">
			<capability description="Study planetary surface, meteorolgy, climate, atmosphere and space plasma">
				<preference type="MISSION" name="METEOROLOGY" modifier="2"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.5"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="8"/>	
				<preference type="SCIENCE" name="COMPUTING" modifier="4"/>								
			</capability>
			<capability description="Test new flexible space suit micro fabric">
				<preference type="MISSION" name="BIOLOGY" modifier="1.3"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="8"/>				
			</capability>
			<capability description="Improve closed-loop life support system">
				<preference type="SCIENCE" name="COMPUTING" modifier="4"/>
				<preference type="SCIENCE" name="MEDICINE" modifier="6"/>	
				<preference type="SCIENCE" name="BOTANY" modifier="3"/>		
				<preference type="SCIENCE" name="BIOLOGY" modifier="3"/>															
			</capability>
		</agenda>
		
		<agenda name="Space Tracking"
				objective="Populate advanced sensors for space observation and tracking platforms"
				findings="Assess locations for placement of terrestrial-based sensors for orbital tracking and observation"
				data="Measure and identify spectral signatures of man-made and natural space objects">
			<capability description="Test designs for fixed ground and mobile observatory ">
				<preference type="MISSION" name="METEOROLOGY" modifier="1.3"/>
				<preference type="SCIENCE" name="ASTRONOMY" modifier="9"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="4"/>	
				<preference type="SCIENCE" name="COMPUTING" modifier="4"/>								
			</capability>
			<capability description="Test radiation-proof fabric and barrier">
				<preference type="MISSION" name="BIOLOGY" modifier="1.5"/>
				<preference type="SCIENCE" name="MEDICINE" modifier="7"/>				
				<preference type="MISSION" name="TRADE" modifier="1"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="4"/>				
				<preference type="SCIENCE" name="ENGINEERING" modifier="4"/>				
			</capability>
			<capability description="Improve methodologies and algorithms for tracking space objects">
				<preference type="SCIENCE" name="PHYSICS" modifier="8"/>
				<preference type="SCIENCE" name="MATHEMATICS" modifier="6"/>
				<preference type="SCIENCE" name="COMPUTING" modifier="8"/>									
			</capability>
		</agenda>

		<agenda name="Surface Operations"
				objective="Push boundaries of surface logistic operations"
				findings="Identify the human factors and logistics concerns in surface operations"
				data="Analyze soil's strength for the suitability of spaceport construction">
			<capability description="Stress test on human endurance">
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.3"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="2"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="2"/>
			</capability>
			<capability description="Test return vehicle capability">
				<preference type="MISSION" name="DELIVERY" modifier="1.6"/>
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="RESCUE_SALVAGE_VEHICLE" modifier="1.3"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.8"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="7"/>					
			</capability>
			<capability description="Characterize dynamics of human interactions">
				<preference type="MISSION" name="TRADE" modifier="1.4"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.4"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="8"/>
			</capability>
			<capability description="Extend EVA operations to climbing caves">
				<preference type="MISSION" name="EXPLORATION" modifier="1.2"/>
				<preference type="MISSION" name="MINING" modifier="1.4"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="5"/>	
				<preference type="SCIENCE" name="ENGINEERING" modifier="7"/>	
			</capability>
		</agenda>
						
		<agenda name="Space Commerce"
				objective="Build up capabilities and infrastructures supporting commerce"
				findings="Spearhead the development of economic framework and policies to address concerns" 
				data="Analyze system deficits that hinder the growth of commerce">
			<capability description="Characterize manufacturing and resource production in relation to local economy">
				<preference type="MISSION" name="TRADE" modifier="2"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.4"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="8"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="4"/>
			</capability>
			<capability description="Test space-ground links">
				<preference type="MISSION" name="METEOROLOGY" modifier="1.3"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="8"/>	
				<preference type="SCIENCE" name="COMPUTING" modifier="4"/>								
			</capability>
			<capability description="Identify social factors in developing commerce">
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.3"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="2"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="2"/>
			</capability>
			<capability description="Conceptualize interplanetary transportation network">
				<preference type="MISSION" name="DELIVERY" modifier="1.9"/>
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="TRADE" modifier="2"/>
				<preference type="MISSION" name="RESCUE_SALVAGE_VEHICLE" modifier="4"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.2"/>
				<preference type="SCIENCE" name="COMPUTING" modifier="4"/>	
				<preference type="SCIENCE" name="MATHEMATICS" modifier="6"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="7"/>
			</capability>
		</agenda>
				
		<!-- https://en.wikipedia.org/wiki/United_Arab_Emirates_Space_Agency
			 https://www.iafastro.org/membership/all-members/uae-space-agency.html -->				
		<agenda name="Space Economy"
				objective="Develop space economic zones"
				findings="Address regulatory concerns in developing space business and infrastructures" 
				data="Gather metrices on commercial space activities">
			<capability description="Spearhead accelerator group">
				<preference type="MISSION" name="TRADE" modifier="2"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.4"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="8"/>
			</capability>
			<capability description="Develop space labs and facilitate knowledge transfer">
				<preference type="SCIENCE" name="ASTRONOMY" modifier="4"/>
				<preference type="SCIENCE" name="CHEMISTRY" modifier="4"/>
				<preference type="SCIENCE" name="COMPUTING" modifier="4"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="4"/>
				<preference type="SCIENCE" name="MEDICINE" modifier="4"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="4"/>							
			</capability>
			<capability description="Supervise and support space government services">
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="TRADE" modifier="1.6"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="2"/>
			</capability>
			<capability description="Establish international partnership in the space sector">
				<preference type="MISSION" name="DELIVERY" modifier="1.5"/>
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="TRADE" modifier="2"/>
				<preference type="MISSION" name="RESCUE_SALVAGE_VEHICLE" modifier="4"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.2"/>
			</capability>
		</agenda>
										
		<agenda name="Space Sustainability"
				objective="Incentivize private and corporate ownership of properties and resources in space"
				findings="Supports statutes to meet the growing demand for sustainable transporation and logistic needs" 
				data="Analyze and rank policies for enhancing mass resource utilization">
			<capability description="Characterize industry opportunities and innovations in the space sector">
				<preference type="MISSION" name="TRADE" modifier="2"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.4"/>
				<preference type="MISSION" name="MINING" modifier="1.4"/>
				<preference type="MISSION" name="COLLECT_REGOLITH" modifier="1.2"/>				
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="8"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="4"/>
			</capability>
			<capability description="Create stable financial avenue based on settlement economic data">
				<preference type="MISSION" name="TRADE" modifier="1.3"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="3"/>	
				<preference type="SCIENCE" name="MATHEMATICS" modifier="6"/>
				<preference type="SCIENCE" name="COMPUTING" modifier="5"/>								
			</capability>
			<capability description="Identify social factors in developing commerce">
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.3"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="2"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="2"/>
			</capability>
			<capability description="Legislate responsible spaceflight framework and guidelines regarding space debris">
				<preference type="SCIENCE" name="COMPUTING" modifier="4"/>	
				<preference type="SCIENCE" name="MATHEMATICS" modifier="6"/>
				<preference type="SCIENCE" name="PHYSICS" modifier="7"/>
			</capability>
		</agenda>

		<!-- https://www.unoosa.org/oosa/en/ourwork/access2space4all/index.html 
			 https://www.space.com/un-unoosa-space-access-partnership.html -->
		<agenda name="Space Accessibility"
				objective="Partner with public and private actors and fund cooperative projects to allow member states to launch space missions"
				findings="Meet the functional criteria of the growing demand for space access and logistic" 
				data="Collect and analyze member states' sustainable development goals">
			<capability description="Contribute to initiaitive in enabling deveoping and emerging countries to grow their space sector">
				<preference type="MISSION" name="TRADE" modifier="2"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.4"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="8"/>
				<preference type="SCIENCE" name="ENGINEERING" modifier="4"/>
			</capability>
			<capability description="Level the playing level and create new sponsorship for emerging players">
				<preference type="MISSION" name="TRADE" modifier="1.3"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="3"/>	
				<preference type="SCIENCE" name="COMPUTING" modifier="6"/>								
			</capability>
			<capability description="Identify social factors in developing partnership">
				<preference type="MISSION" name="EMERGENCY_SUPPLY" modifier="1.3"/>
				<preference type="MISSION" name="EXPLORATION" modifier="1.3"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="2"/>
				<preference type="SCIENCE" name="PSYCHOLOGY" modifier="2"/>
			</capability>
			<capability description="Develop infrastructure, faciltiy and service as a part 
				of a high impact and high visibility initiative ">
				<preference type="MISSION" name="DELIVERY" modifier="1.9"/>
				<preference type="MISSION" name="TRADE" modifier="2"/>
				<preference type="MISSION" name="TRAVEL_TO_SETTLEMENT" modifier="1.2"/>
				<preference type="SCIENCE" name="COMPUTING" modifier="6"/>	
			</capability>
		</agenda>		
	</agendas>

	<!--  Reporting authorities. The code attribute must match
		the ReportingAuthorityType enum -->
	<authorities>
		<authority code="AEB" name="Agencia Espacial Brasileira" corporation="false"
					agenda="Space Tracking" gender-ratio="0.85">
			<country name="Brazil"/>
			<settlement-name name="Alcantara" />
			<settlement-name name="Antonina" />
			<settlement-name name="Antonio Prado" />
			<settlement-name name="Escola" />
			<settlement-name name="Florianopolis" />
			<settlement-name name="Morretes" />		
			<settlement-name name="Paraty" />
			<settlement-name name="Sao Sebastiao" />	

			<rover-name name="Agrale" />  
			<rover-name name="Lobini" />  
			<rover-name name="Marcopolo" />    