<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE mineral-concentrations [
	<!ELEMENT mineral-concentrations (mineral*)>
	<!ELEMENT mineral (locale-list)>
	<!ATTLIST mineral name CDATA #REQUIRED>
	<!ATTLIST mineral frequency (common|uncommon|rare|very_rare) #REQUIRED>
	<!ELEMENT locale-list (locale+)>
	<!ELEMENT locale EMPTY>
	<!ATTLIST locale name (volcanic|sedimentary|crater) #REQUIRED>
]>

<!-- List of all mineral concentrations that can be mined. -->
<mineral-concentrations>

	<!-- Hematite is an iron ore. -->
	<!-- http://en.wikipedia.org/wiki/Hematite -->
	<!-- frequency - how common are the mineral concentrations? -->
	<!-- Valid values: "common", "uncommon", "rare", "very_rare" -->
	<!-- 
		1. https://science.nasa.gov/science-news/science-at-nasa/2001/ast28mar_1
		
		In 1998, an infrared spectrometer on NASA's Mars Global Surveyor (MGS) spacecraft 
		detected a substantial deposit of gray hematite near the Martian equator, in a 500 
		km-wide region called Sinus Meridiani. 
		
		The discovery raised the tantalizing possibility that hot springs were once active
		on Mars.
		
		Gray hematite has the same chemical formula (Fe2O3) as its rusty-red cousin, but 
		a different crystalline structure. Red rust is fine and powdery; typical grains 
		are hundreds of nanometers to a few microns across. Gray hematite crystals are 
		larger, like grains of sand.

		Red and gray iron oxides on Mars are different forms of the same 
		mineral. 
		
		Ground up the gray hematite into a fine powder it would turn red because the 
		smaller grains scatter red light.

		The coarse-grained structure of gray hematite is important because "to get that 
		kind of coarsening of the crystallinity, you would need to have a reasonable 
		amount of water available" where the hematite formed.
		
		Some of them, like carbonates, would also indicate that standing bodies of 
		water were present on the surface.
		
		Hematite minerals, on the other hand, might have been formed by hydrothermal
		water deep underground.
		
		2. https://www.psi.edu/sites/default/files/newsletter/winter02/Winter2002.pdf
			
		The mineral the TES instrument unequivocally identified is gray hematite 
		(Fe2O3), an oxide mineral that occurs on Earth as well as Mars, whose 
		chemistry is similar to that of common rust. 
		
		The hematite found on Mars occurs in both fine-grained and coarse-grained 
		varieties.  Fine-grained hematite (whose grain diameters are <5-10 microns)
		gives Mars its red color, which is why Mars is called the “Red Planet”.  
		 
		This fine-grained hematite is dispersed within the copious dust that gets 
		blown around the planet during the seasonal Martian dust storms and is 
		seen as the lighter-colored regions on Mars.  In contrast, coarser-grained
		hematite (>10 micron-diameter grains) is gray, not red like the finer-
		grained hematite in the Martian dust, since the finer grains scatter the
		red end of the solar spectrum.
		  
		A global investigation of Mars by the TES instrument has led to 
		identification of only three main areas of gray hematite exposed at the 
		surface of the entire planet.  
		
		These gray hematite deposits all occur in darker regions on Mars near 
		the equator including an area called Sinus Meridiani, in a large impact
		crater called Aram, and within the Valles Marineris canyon system.  
		
		It is possible that the finegrained hematite originated through weathering
		of gray hematite like those three areas near the equator.
		
		It is a common rock-forming mineral found in sedimentary, metamorphic, 
		and igneous rocks at locations throughout the world.
	-->
	<mineral name="Hematite" frequency="common">
		<locale-list>
			<!-- locale topographical regions the mineral is located. -->
			<!-- Valid values: "volcanic", "sedimentary", "crater" -->
			<locale name="volcanic" />
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Magnetite is an iron ore with volcanic and metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Magnetite -->
	<!-- 
		1. https://www.nature.com/articles/s41561-018-0203-8
		
		Experiments show that pH variations within anoxic basaltic waters trigger 
		a series of mineral transformations that rapidly generate magnetite and 
		H2(aq). Magnetite continues to form through this mechanism despite high 
		partial pressure of carbon dioxide (pCO2) and supersaturation with respect
		to Fe-carbonate minerals. Reactive transport simulations that incorporate 
		these experimental data show that groundwater infiltration into a lake 
		equilibrated with a CO2-rich atmosphere can trigger the production of 
		both magnetite and H2(aq) in the mudstones. H2(aq), generated at 
		concentrations that would readily exsolve from solution, is capable of 
		increasing annual mean surface temperatures above freezing in CO2-dominated
		atmospheres. We therefore suggest that magnetite authigenesis could have
		provided a short-term feedback for stabilizing liquid water, as well as
		a principal feedstock for biologically relevant chemical reactions, at 
		the early Martian surface.
		  
		2. https://www.pnas.org/doi/10.1073/pnas.241387898
		
		The case for former Martian life now rests on the identification of a small
		subset of the magnetite crystals in ALH84001 as biogenic in origin. 
	-->
	<mineral name="Magnetite" frequency="rare">
		<locale-list>
			<locale name="volcanic" />
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Magnesite is a magnesium carbonate with metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Magnesite -->
	<!-- 
		Magnesite is a mineral with the chemical formula MgCO3 
		(magnesium carbonate). Iron, manganese, cobalt, and nickel may occur 
		as admixtures, but only in small amounts.
	
		1. http://en.wikipedia.org/wiki/Magnesite 
		
	    Magnesite was detected in meteorite ALH84001 and on planet Mars itself. 
	    Magnesite was identified on Mars using infrared spectroscopy from satellite 
	    orbit. Near Jezero Crater, Mg-carbonates have been detected and reported to
	    have formed in lacustrine environment prevailing there.[28] Controversy 
	    still exists over the temperature of formation of these carbonates. 
	    
	    Low-temperature formation has been suggested for the magnesite from the 
	    Mars-derived ALH84001 meteorite.

		Magnesium-rich olivine (forsterite) favors production of magnesite from 
		peridotite. Iron-rich olivine (fayalite) favors production of magnetite-
		magnesite-silica compositions.
	-->
	<mineral name="Magnesite" frequency="rare">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Olivine is a magnesium iron silicate found in meteorites. -->
 	<!-- 
 		1. https://zenodo.org/record/1230836
 		
 		30,000-square-kilometer area rich in olivine in the Nili Fossae region of Mars. 
 		Nili Fossae has been interpreted as a complex of grabens and fractures related to 
 		the formation of the Isidis impact basin.
 	
 		2. http://en.wikipedia.org/wiki/Olivine 
 	
 		Mg-rich olivine has also been discovered in meteorites, on the Moon and Mars, falling 
 		into infant stars, as well as on asteroid 25143 Itokawa.
 		
 		3. https://en.wikipedia.org/wiki/Composition_of_Mars
 		
     	The mineral olivine occurs all over the planet, but some of the largest concentrations 
     	are in Nili Fossae, an area containing Noachian-aged rocks. Another large olivine-rich
     	outcrop is in Ganges Chasma, an eastern side chasm of Valles Marineris. 
     	
     	Olivine weathers rapidly into clay minerals in the presence of liquid water. 
     	Therefore, areas with large outcroppings of olivine-bearing rock indicate that liquid 
     	water has not been abundant since the rocks formed.
 	-->
	<mineral name="Olivine" frequency="uncommon">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Goethite is an iron ore that has metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Goethite -->
	<mineral name="Goethite" frequency="common">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Kamacite is an iron-nickel mineral found in meteorites. -->
	<!-- http://en.wikipedia.org/wiki/Kamacite -->
	<mineral name="Kamacite" frequency="common">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Taenite is an iron-nickel mineral found in meteorites. -->
	<!-- http://en.wikipedia.org/wiki/Taenite -->
	<mineral name="Taenite" frequency="common">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Chalcopyrite is a copper sulfide mineral. -->
	<!-- http://en.wikipedia.org/wiki/Chalcopyrite -->
	<mineral name="Chalcopyrite" frequency="uncommon">
		<locale-list>
			<locale name="sedimentary" />
			<locale name="volcanic" />
		</locale-list>
	</mineral>
	
	<!-- Malachite is a copper carbonate mineral. -->
	<!-- http://en.wikipedia.org/wiki/Malachite -->
	<mineral name="Malachite" frequency="uncommon">
		<locale-list>
			<locale name="sedimentary" />
			<locale name="volcanic" />
		</locale-list>
	</mineral>
	
	<!-- Sylvite is a salt concentration of potassium chloride. -->
	<!-- http://en.wikipedia.org/wiki/Sylvite -->
	<mineral name="Sylvite" frequency="common">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- jarosite, Plagioclase, Feldspar, High-Ca Pyroxene, Low-Ca Pyroxene, Quartz,
    Amphibole, Silicates -->
	
	
</mineral-concentrations>