<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE people-configuration [
	<!ELEMENT people-configuration (
	person-attributes,
	characteristics,
	personality-types,
	training-list)>

	<!ELEMENT person-attributes (
	base-carrying-capacity,
	low-activity-metaboic-load-o2-consumption-rate,
	nominal-activity-metaboic-load-o2-consumption-rate,
	high-activity-metaboic-load-o2-consumption-rate,
	co2-expelled-rate,
	water-consumption-rate,
	water-usage-rate,
	grey-to-black-water-ratio,
	dessert-consumption-rate,
	food-consumption-rate,
	dehydration-start-time,
	starvation-start-time,
	min-air-pressure,
	min-o2-partial-pressure,
	min-temperature,
	max-temperature,
	stress-breakdown-chance,
	high-fatigue-collapse-chance)
	>

	<!ELEMENT base-carrying-capacity EMPTY>
	<!ATTLIST base-carrying-capacity value CDATA #REQUIRED>

	<!ELEMENT low-activity-metaboic-load-o2-consumption-rate EMPTY>
	<!ATTLIST low-activity-metaboic-load-o2-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT nominal-activity-metaboic-load-o2-consumption-rate EMPTY>
	<!ATTLIST nominal-activity-metaboic-load-o2-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT high-activity-metaboic-load-o2-consumption-rate EMPTY>
	<!ATTLIST high-activity-metaboic-load-o2-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT co2-expelled-rate EMPTY>
	<!ATTLIST co2-expelled-rate value CDATA #REQUIRED>

	<!ELEMENT water-consumption-rate EMPTY>
	<!ATTLIST water-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT water-usage-rate EMPTY>
	<!ATTLIST water-usage-rate value CDATA #REQUIRED>

	<!ELEMENT grey-to-black-water-ratio EMPTY>
	<!ATTLIST grey-to-black-water-ratio value CDATA #REQUIRED>

	<!ELEMENT dessert-consumption-rate EMPTY>
	<!ATTLIST dessert-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT food-consumption-rate EMPTY>
	<!ATTLIST food-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT dehydration-start-time EMPTY>
	<!ATTLIST dehydration-start-time value CDATA #REQUIRED>

	<!ELEMENT starvation-start-time EMPTY>
	<!ATTLIST starvation-start-time value CDATA #REQUIRED>

	<!ELEMENT min-air-pressure EMPTY>
	<!ATTLIST min-air-pressure value CDATA #REQUIRED>

	<!ELEMENT min-o2-partial-pressure EMPTY>
	<!ATTLIST min-o2-partial-pressure value CDATA #REQUIRED>

	<!ELEMENT min-temperature EMPTY>
	<!ATTLIST min-temperature value CDATA #REQUIRED>

	<!ELEMENT max-temperature EMPTY>
	<!ATTLIST max-temperature value CDATA #REQUIRED>

	<!ELEMENT stress-breakdown-chance EMPTY>
	<!ATTLIST stress-breakdown-chance value CDATA #REQUIRED>

	<!ELEMENT high-fatigue-collapse-chance EMPTY>
	<!ATTLIST high-fatigue-collapse-chance value CDATA #REQUIRED>

	<!ELEMENT gender-male-percentage EMPTY>
	<!ATTLIST gender-male-percentage value CDATA #REQUIRED>

	<!ELEMENT characteristics EMPTY>
	<!ATTLIST characteristics average-male-height CDATA #REQUIRED>
	<!ATTLIST characteristics average-female-height CDATA #REQUIRED>
	<!ATTLIST characteristics average-male-weight CDATA #REQUIRED>
	<!ATTLIST characteristics average-female-weight CDATA #REQUIRED>


	<!ELEMENT personality-types (mbti*)>

	<!ELEMENT mbti EMPTY>
	<!ATTLIST mbti type CDATA #REQUIRED>
	<!ATTLIST mbti percentage CDATA #REQUIRED>
	
	<!ELEMENT training-list (training*)>
	<!ELEMENT training (benefit*)>
	<!ATTLIST training name CDATA #REQUIRED>
	<!ELEMENT benefit EMPTY>
	<!ATTLIST benefit role CDATA #REQUIRED>
	<!ATTLIST benefit modifier CDATA #REQUIRED>
]>

<people-configuration>
	<person-attributes>
		<!-- The base load-carrying capacity of an adult person in kg. Will be modified by age and attribute of a person -->
		<base-carrying-capacity value="30" />

		<!-- The average amount of oxygen breathed in by a person on each Sol for
			low, nominal & high metabolic activities -->
		<!-- Default: 0.78, 0.84, 0.96 [in kg] -->
		<low-activity-metaboic-load-o2-consumption-rate
			value="0.78" />
		<nominal-activity-metaboic-load-o2-consumption-rate
			value="0.84" />
		<high-activity-metaboic-load-o2-consumption-rate
			value="0.96" />
		<!-- e.g. total surface requirement for a crew of 3 during a 500-day surface
			stay based on nominal activity is ~1260 kg of O2 -->

		<!-- The average amount of carbon dioxide expelled by a person on each Sol
			for high metabolic activities -->
		<!-- Default: 1.0433 [in kg/sol] -->
		<co2-expelled-rate value="1.0433" />
		<!--

		Note: this is in contrast with the value of 700 to 900 mL CO2 exhaled
			due to norminal activity from https://www.globe.gov/explore-science/scientists-blog/archived-posts/sciblog/index.html_p=183.html

		// NOTE: Assume the EVA Suit has pump system to vent out all CO2 to prevent the built-up.
		// The breath rate is 12 to 25 per minute.
		// Size of breath is 500 mL.
		// Percent CO2 exhaled is 4%.
		// CO2 per breath is approx 0.04g = 2g/L x 4% x 500mL.

		-->


		<!-- The normal average amount of water drank by a person on each sol -->
		<!-- Default: 2.5 -->
		<water-consumption-rate value="2.5" />

		<!-- The normal average amount (kg) of hygiene water (toilet, shower, clothing
			wash) toilet, etc.) by a person each martian sol -->
		<!-- This compares with ~288 kg water usage per person per day in US -->
		<!-- Note : 1 US gallon = 3.79 kg or liter (water) -->
		<!-- Instead of consuming an average of 50 liters to take a shower (typical
			on Earth), denizens of the ISS uses 4 liters to bathe. -->
		<!-- Default: 20.0 -->
		<water-usage-rate value="20.0" />

		<!-- The fictitious ratio denoting the amount of grey water and black water
			generated per unit water usage -->
		<!-- Default: 4.0. This translates to 80% grey water and 20% black water
			(OR 4 to 1) -->
		<grey-to-black-water-ratio value="4.0" />

		<!-- The normal average amount of dessert (kg) in dry weight eaten by a
			person on each Martian Sol -->
		<!-- Default: 0.3 dry Weight (arbitrary), note that beverage has arbitrary
			predefined weight -->
		<dessert-consumption-rate value="0.2" />

		<!-- The normal average amount of food (kg) in dry weight eaten by a person
			on each Martian Sol -->
		<!-- Default: 0.62 dry Weight -->
		<food-consumption-rate value="0.62" />

		<!-- Number of sols without water before dehydration kicks in -->
		<!-- Default: 2.0 -->
		<dehydration-start-time value="3.0" />

		<!-- Number of sols without food before starvation kicks in -->
		<!-- Default: 7.0 -->
		<starvation-start-time value="7.0" />

		<!-- Minimum air pressure (kPa) a person can withstand without harm At least
			170 mb (2.5 psi, or 17.24 kPa) without a spacesuit, Note : 1kPa = 0.1450377
			psi see "How To Live On Mars" per Zubrin, P.91 -->
		<!-- Default: 17.24 -->
		<min-air-pressure value="17.24" />

		<!-- The absolute minimum oxygen partial pressure -->
		<!-- According to https://en.wikipedia.org/wiki/Mars_suit#Breathing for
			a space suit, the absolute minimum safe oxygen requirement is a partial pressure
			of 11.94 kPa (1.732 psi) -->
		<!-- Default: 11.94 -->
		<min-o2-partial-pressure value="11.94" />

		<!-- Minimum temperature (degrees celsius) a person can withstand without
			harm -->
		<!-- Default: 0 degrees celsius -->
		<min-temperature value="-20.0" />

		<!-- Maximum temperature (degrees celsius) a person can withstand without
			harm -->
		<!-- Default: 48 degrees celsius -->
		<max-temperature value="48.0" />

		<!-- Base percent chance per millisol that a person at high stress will
			have a panic attack or depression. -->
		<!-- See medical complaint: "Panic Attack" and "Depression" in medical.xml. -->
		<!-- Default: 10 [in percentage] -->
		<stress-breakdown-chance value="10.0" />

		<!-- Base percent chance per millisol that a person at high fatigue will
			collapse. -->
		<!-- See medical complaint: "High Fatigue Collapse" in medical.xml. -->
		<!-- Default: 10 [in percentage] -->
		<high-fatigue-collapse-chance value="10.0" />
	</person-attributes>

	<!-- Average characteristics -->
    <characteristics average-male-height="176.5" average-female-height="162.5"
	            average-male-weight="72" average-female-weight="65"/>

	<!-- Myers-Briggs Type Indicator: http://www.wikipedia.org/wiki/MBTI -->
	<!-- engineers or computer programmers. -->
	<!-- The Proposed average percentages of the 16 MBTI among settlers are
		as follows -->
	<personality-types>
		<!-- Note: The total percentage for all personality types must equal 100%. -->
		<mbti type="ISTP" percentage="3.0" />
		<mbti type="ISTJ" percentage="19.0" />
		<mbti type="ISFP" percentage="2.0" />
		<mbti type="ISFJ" percentage="8.0" />
		<mbti type="INTP" percentage="6.0" />
		<mbti type="INTJ" percentage="7.0" />
		<mbti type="INFP" percentage="6.0" />
		<mbti type="INFJ" percentage="5.0" />
		<mbti type="ESTP" percentage="2.0" />
		<mbti type="ESTJ" percentage="13.0" />
		<mbti type="ESFP" percentage="2.0" />
		<mbti type="ESFJ" percentage="8.0" />
		<mbti type="ENTP" percentage="4.0" />
		<mbti type="ENTJ" percentage="3.0" />
		<mbti type="ENFP" percentage="7.0" />
		<mbti type="ENFJ" percentage="5.0" />
	</personality-types>

	<training-list>
		<training name="MARS_V_GOBI">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="3"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="2"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="4"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="5"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="6"/>
		</training>
		<training name="NASA_CHAPEA">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="5"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="2"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="5"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="6"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="7"/>
		</training>
		<training name="UNDERGROUND_CAVES_EXPLORATION">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="5"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="3"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="5"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="7"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="6"/>
		</training>
		<training name="BIOETHICAL">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="8"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="7"/>
			<benefit role="MISSION_SPECIALIST" modifier="2"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="2"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="5"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="6"/>
		</training>
		<training name="EXTREME_ENV_OPS">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="6"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="2"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training> 
		<training name="NASA_DESERT_RATS">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="2"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="3"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training>
		<training name="SURVIVAL_TRAINING">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="6"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="7"/>
			<benefit role="SAFETY_SPECIALIST" modifier="5"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="3"/>
		</training>
		<training name="SCUBA_DIVING_MASTER">
			<benefit role="COMPUTING_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="5"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="6"/>
			<benefit role="SAFETY_SPECIALIST" modifier="6"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="2"/>
		</training>
		<training name="FLIGHT_SAFETY">
			<benefit role="COMPUTING_SPECIALIST" modifier="4"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="2"/>
			<benefit role="SAFETY_SPECIALIST" modifier="8"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="5"/>
		</training>	
		<training name="SEARCH_AND_RESCUE">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="3"/>
			<benefit role="MISSION_SPECIALIST" modifier="8"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="7"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="1"/>
		</training>
		<training name="MOUNTAINEERING_MASTER">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="1"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="7"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="9"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="8"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="2"/>
		</training>
		<training name="AIRBORNE_AND_RANGER_SCHOOL">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="4"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="9"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="6"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="8"/>
			<benefit role="SAFETY_SPECIALIST" modifier="4"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="1"/>
		</training>
		<training name="HAUGHTON_MARS_GEOLOGICAL">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="6"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="5"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training>
		<training name="HALO_JUMPMASTER">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="3"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="9"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="8"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="2"/>
		</training>
		<training name="MISHAP_INVESTIGATION">
			<benefit role="COMPUTING_SPECIALIST" modifier="3"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="7"/>
			<benefit role="MISSION_SPECIALIST" modifier="5"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="2"/>
			<benefit role="SAFETY_SPECIALIST" modifier="9"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="5"/>
		</training>
		<training name="MARS_500_C">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="6"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="4"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="4"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="7"/>
		</training>
		<training name="MARS_ANALOG_ENVIRONMENT">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="7"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="4"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="5"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training>
		<training name="UNDERSEA_MISSION">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="3"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="3"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training>
		<training name="MILITARY_DEPLOYMENT">
			<benefit role="COMPUTING_SPECIALIST" modifier="2"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="9"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="5"/>
		</training>
		<training name="AVIATION_CERTIFICATION">
			<benefit role="COMPUTING_SPECIALIST" modifier="5"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="4"/>
			<benefit role="MISSION_SPECIALIST" modifier="3"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="3"/>
			<benefit role="SAFETY_SPECIALIST" modifier="9"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="2"/>
		</training>
		<training name="ANTARCTICA_EDEN_ISS">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="8"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="5"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="7"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="6"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="9"/>
		</training> 		
		<training name="MARS_TWO_FINAL_100">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="5"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="5"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="4"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="3"/>
		</training>
	</training-list>	
</people-configuration>
