<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE resupply-list [
	<!ELEMENT resupply-list (resupply*)>
	<!ELEMENT resupply (building*, vehicle*, equipment*, resource*, part*, part-package*)>
	<!ATTLIST resupply name CDATA #REQUIRED>
	<!ATTLIST resupply person CDATA #IMPLIED>
	<!ELEMENT building EMPTY>
	<!ATTLIST building zone CDATA #IMPLIED>	
	<!ATTLIST building type CDATA #REQUIRED>
	<!ATTLIST building width CDATA #IMPLIED>
	<!ATTLIST building length CDATA #IMPLIED>
	<!ATTLIST building xloc CDATA #REQUIRED>
	<!ATTLIST building yloc CDATA #REQUIRED>
	<!ATTLIST building facing CDATA #REQUIRED>
	<!ELEMENT vehicle EMPTY>
	<!ATTLIST vehicle type CDATA #REQUIRED>
	<!ATTLIST vehicle number CDATA #REQUIRED>
	<!ELEMENT equipment EMPTY>
	<!ATTLIST equipment type CDATA #REQUIRED>
	<!ATTLIST equipment number CDATA #REQUIRED>
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource name CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part type CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT part-package EMPTY>
	<!ATTLIST part-package name CDATA #REQUIRED>
	<!ATTLIST part-package number CDATA #REQUIRED>
]>

<!-- Settlement resupply missions from Earth. -->
<resupply-list>

	<resupply name="Standard Resupply 1">
	
	    <!-- Containers-->
		<equipment type="barrel" number="24" />
		<equipment type="bag" number="24" />
		<equipment type="gas canister" number="24" />		
		<equipment type="large bag" number="24" />
		<equipment type="specimen box" number="24" />
    	<equipment type="thermal bottle" number="8" />	
 	    <equipment type="wheelbarrow" number="8" />	   	
	
	    <!-- Life Support Resources -->
	    <resource name="food" amount="1000.0" />
	    <resource name="water" amount="4000.0" />
	    <resource name="oxygen" amount="1000.0" />

		<!-- Gases -->
	    <resource name="argon" amount="60.0" />
	
		<!-- Crop related -->
	    <resource name="fertilizer" amount="50.0" />
	
	    <!-- Crop tissues -->
	    <resource name="blueberry tissue" amount="1.0" />
	    <resource name="cabbage tissue" amount="1.0" />
	    <resource name="carrot tissue" amount="1.0" />
	    <resource name="celery tissue" amount="1.0" />
	    <resource name="corn tissue" amount="1.0" />
	
	    <resource name="cranberry tissue" amount="1.0" />
	    <resource name="cucumber tissue" amount="1.0" />
	    <resource name="garlic tissue" amount="1.0" />
	    <resource name="ginger tissue" amount="1.0" />
	    <resource name="green bell pepper tissue" amount="1.0" />
	
	    <resource name="kidney bean tissue" amount="1.0" />
	    <resource name="lettuce tissue" amount="1.0" />
	    <resource name="morel mushroom tissue" amount="1.0" />
	    <resource name="peanut tissue" amount="1.0" />
	    <resource name="peas tissue" amount="1.0" />
	    
	    <resource name="potato tissue" amount="1.0" />
	    <resource name="quinoa tissue" amount="1.0" />
	    <resource name="radish tissue" amount="1.0" />	    
	    <resource name="red beet tissue" amount="1.0" />
	    <resource name="rice tissue" amount="1.0" />
	    
	    <resource name="sesame tissue" amount="1.0" />	    
	    <resource name="soybean tissue" amount="1.0" />
	   	<resource name="spring onion tissue" amount="1.0" />
	    <resource name="strawberry tissue" amount="1.0" />
	    <resource name="sugarcane tissue" amount="1.0" />
	    
	   	<resource name="sweet potato tissue" amount="1.0" />
	    <resource name="swiss chard tissue" amount="1.0" />
	    <resource name="taro tissue" amount="1.0" />
	    <resource name="tomato tissue" amount="1.0" />
	    <resource name="wheat tissue" amount="1.0" />
	    
	    <resource name="white mustard tissue" amount="1.0" />
	    <resource name="white onion tissue" amount="1.0" />
	    <resource name="yam tissue" amount="1.0" />
	    
	    <!-- Seeds -->
	    <resource name="mustard seed" amount="50.0" />
	    <resource name="sesame seed" amount="50.0" />
	
	    <!-- Kitchen Resources -->
	    <resource name="chlorine" amount="50.0" />
	    <resource name="Sodium Hypochlorite" amount="20.0" />
	    <resource name="Acetic Acid Bacteria" amount="20.0" />
	    <resource name="Nitrosomonas spp" amount="20.0" />
	    <resource name="Nitrospira spp" amount="20.0" />
	    
	    <resource name="Rhizobia" amount="20.0" />
	    <resource name="bisphenol-A" amount="100.0" />
	    <resource name="toilet tissue" amount="100.0" />
	    <resource name="paper" amount="100.0" />
	    <resource name="napkin" amount="100.0" />
	    
	    <resource name="bleaching chemical" amount="50.0" />
	    <resource name="Baking Powder" amount="100.0" />
	    <resource name="pulp" amount="100.0" />
	    <resource name="Honey" amount="100.0" />
	    <resource name="Yeast" amount="50.0" />
	    
	    <resource name="Epsom Salt" amount="50.0" />
	    <resource name="Table Salt" amount="50.0" />
	    <resource name="Sugar" amount="50.0" />	    
	
	    <!-- Food Derived Items -->
	    <resource name="mustard" amount="50.0" />
	    <resource name="Tofu" amount="50.0" />
	    <resource name="Roasted Peanut" amount="50.0" />
	    <resource name="White Bread" amount="50.0" />
	    <resource name="White Bun" amount="50.0" />
	    
	    <resource name="Veggie Patty" amount="50.0" />
	    <resource name="Wheat Bread" amount="50" />
	    <resource name="Wheat Bun" amount="50" />
	    <resource name="Soy Protein" amount="50.0" />
	    <resource name="Peanut Butter" amount="50.0" />
	    
	    <resource name="Soy Sprout" amount="50.0" />
	    <resource name="Rice Vinegar" amount="50.0" />
	    <resource name="Soy Sauce" amount="50.0" />
	    <resource name="Soy Flour" amount="50.0" />
	    <resource name="Wheat Flour" amount="50.0" />
	    	    
	    <resource name="Cane Fiber" amount="100.0" />
	    
	    <resource name="Soybean Oil" amount="50.0" />
	    <resource name="Peanut Oil" amount="50.0" />
	    <resource name="Garlic Oil" amount="50.0" />
	    <resource name="Sesame Oil" amount="50.0" />
	    
	    <!-- Dessert -->
	    <resource name="Granola Bar" amount="10.0" />
	    <resource name="Soymilk" amount="50.0" />
	    
	    <!-- Utility Resources -->
	    <resource name="iron powder" amount="10.0" />  
	
	        	
	</resupply>
	
	<resupply name="Food Resupply 1">
	
		<!-- Crop related -->
	    <resource name="fertilizer" amount="50.0" />
	    <resource name="Olive" amount="50.0" />
	    	
	    <!-- Crop tissues -->
	    <resource name="blueberry tissue" amount="1.0" />
	    <resource name="cabbage tissue" amount="1.0" />
	    <resource name="carrot tissue" amount="1.0" />
	    <resource name="celery tissue" amount="1.0" />
	    <resource name="corn tissue" amount="1.0" />
	
	    <resource name="cranberry tissue" amount="1.0" />
	    <resource name="cucumber tissue" amount="1.0" />
	    <resource name="garlic tissue" amount="1.0" />
	    <resource name="ginger tissue" amount="1.0" />
	    <resource name="green bell pepper tissue" amount="1.0" />
	
	    <resource name="kidney bean tissue" amount="1.0" />
	    <resource name="lettuce tissue" amount="1.0" />
	    <resource name="morel mushroom tissue" amount="1.0" />
	    <resource name="peanut tissue" amount="1.0" />
	    <resource name="peas tissue" amount="1.0" />
	    
	    <resource name="potato tissue" amount="1.0" />
	    <resource name="quinoa tissue" amount="1.0" />
	    <resource name="radish tissue" amount="1.0" />	    
	    <resource name="red beet tissue" amount="1.0" />
	    <resource name="rice tissue" amount="1.0" />
	    
	    <resource name="sesame tissue" amount="1.0" />	    
	    <resource name="soybean tissue" amount="1.0" />
	   	<resource name="spring onion tissue" amount="1.0" />
	    <resource name="strawberry tissue" amount="1.0" />
	    <resource name="sugarcane tissue" amount="1.0" />
	    
	   	<resource name="sweet potato tissue" amount="1.0" />
	    <resource name="swiss chard tissue" amount="1.0" />
	    <resource name="taro tissue" amount="1.0" />
	    <resource name="tomato tissue" amount="1.0" />
	    <resource name="wheat tissue" amount="1.0" />
	    
	    <resource name="white mustard tissue" amount="1.0" />
	    <resource name="white onion tissue" amount="1.0" />
	    <resource name="yam tissue" amount="1.0" />
	    
	    <!-- Seeds -->
	    <resource name="mustard seed" amount="50.0" />
	    <resource name="sesame seed" amount="50.0" />
	
	    <!-- Food Derived Items -->
	    <resource name="mustard" amount="50.0" />
	
	    <!-- Kitchen Resources -->
	    <resource name="chlorine" amount="50.0" />
	    <resource name="Sodium Hypochlorite" amount="20.0" />
	    <resource name="Acetic Acid Bacteria" amount="20.0" />
	    <resource name="Nitrosomonas spp" amount="20.0" />
	    <resource name="Nitrospira spp" amount="20.0" />
	    
	    <resource name="Rhizobia" amount="20.0" />
	    <resource name="bisphenol-A" amount="100.0" />
	    <resource name="toilet tissue" amount="100.0" />
	    <resource name="paper" amount="100.0" />
	    <resource name="napkin" amount="100.0" />
	    
	    <resource name="bleaching chemical" amount="50.0" />
	    <resource name="Baking Powder" amount="100.0" />
	    <resource name="pulp" amount="100.0" />
	    <resource name="Honey" amount="100.0" />
	    <resource name="Yeast" amount="50.0" />
	    
	    <resource name="Epsom Salt" amount="50.0" />
	    <resource name="Table Salt" amount="50.0" />
	    <resource name="Sugar" amount="50.0" />	    
	
	    <!-- Food Derived Items -->
	    <resource name="mustard" amount="50.0" />
	    <resource name="Tofu" amount="50.0" />
	    <resource name="Roasted Peanut" amount="50.0" />
	    <resource name="White Bread" amount="50.0" />
	    <resource name="White Bun" amount="50.0" />
	    
	    <resource name="Veggie Patty" amount="50.0" />
	    <resource name="Wheat Bread" amount="50" />
	    <resource name="Wheat Bun" amount="50" />
	    <resource name="Soy Protein" amount="50.0" />
	    <resource name="Peanut Butter" amount="50.0" />
	    
	    <resource name="Soy Sprout" amount="50.0" />
	    <resource name="Soybean Oil" amount="50.0" />
	    <resource name="Peanut Oil" amount="50.0" />
	    <resource name="Garlic Oil" amount="50.0" />
	    <resource name="Sesame Oil" amount="50.0" />
		<resource name="Olive Oil" amount="50.0" />    
	    
	    <resource name="Cane Fiber" amount="100.0" />
	    <resource name="Rice Vinegar" amount="50.0" />
	    <resource name="Soy Sauce" amount="50.0" />
	    <resource name="Soymilk" amount="50.0" />
	    <resource name="Soy Flour" amount="50.0" />
	    
	    <resource name="Wheat Flour" amount="50.0" />
	    <resource name="Granola Bar" amount="10.0" />
	    <resource name="Protein Bar" amount="10.0" />	    
	    

	</resupply>

	<!-- Resupply mission from Earth. -->
	<!-- name: the unique name of the resupply mission. -->
	<resupply name="Resupply for Phase 1" person="4">
			
		<!-- New equipment -->
		<!-- type: the type of equipment. -->
		<!-- number: the number of this type of equipment. -->		
		
		<equipment type="EVA Suit" number="8" />
							
		 <!-- Containers-->
		<equipment type="barrel" number="80" />
		<equipment type="bag" number="80" />
		<equipment type="gas canister" number="80" />		
		<equipment type="large bag" number="80" />
		<equipment type="specimen box" number="80" />
    	<equipment type="thermal bottle" number="4" />			
   	    <equipment type="wheelbarrow" number="4" />
   	    

		<!-- Resource provided in this resupply. -->
		<!-- type: the type of resource (see resources.txt) -->
		<!-- amount: the amount of the resource (kg) -->

		<!-- Part packages (see part_packages.xml) -->
		<!-- name: the part package name. -->
		<!-- number: the number of packages. -->
		<part-package name="package 2" number="1" />

	</resupply>

	<resupply name="Resupply for Phase 2" person="4">
					
		<vehicle type="Explorer Rover" number="1" />
		<vehicle type="Transport Rover" number="1" />
		<vehicle type="Light Utility Vehicle" number="1" />
		<vehicle type="Delivery Drone" number="1" />
					
	    
		<equipment type="EVA Suit" number="8" />
							
		 <!-- Containers-->
		<equipment type="barrel" number="80" />
		<equipment type="bag" number="80" />
		<equipment type="gas canister" number="80" />		
		<equipment type="large bag" number="80" />
		<equipment type="specimen box" number="80" />
    	<equipment type="thermal bottle" number="4" />	
 	    <equipment type="wheelbarrow" number="2" />

		
		<resource name="hydrogen" amount="1000.0" />
		<resource name="food" amount="1657.0" />
		
		<part-package name="package 3" number="1" />
		
	</resupply>

	<resupply name="Resupply for Phase 3" person="4">
			
		<vehicle type="Long Range Explorer" number="2" />
		<vehicle type="Transport Rover" number="2" />
		<vehicle type="Light Utility Vehicle" number="1" />
		<vehicle type="Delivery Drone" number="1" />
		
		<equipment type="EVA Suit" number="24" />
		
		 <!-- Containers-->
		<equipment type="barrel" number="80" />
		<equipment type="bag" number="80" />
		<equipment type="gas canister" number="80" />		
		<equipment type="large bag" number="80" />
		<equipment type="specimen box" number="80" />
    	<equipment type="thermal bottle" number="12" />	
 	    <equipment type="wheelbarrow" number="12" />
		
		<resource name="hydrogen" amount="1000.0" />
		<resource name="food" amount="4970.0" />
		
		<part-package name="package 4" number="1" />
		
	</resupply>

</resupply-list>