=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/crew/crew.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="personality-trait">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="value" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="natural-attribute">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="value" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="skill">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="level" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="relationship">
        <xs:complexType>
            <xs:attribute name="person-name" type="xs:string"/>
            <xs:attribute name="opinion" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personality-trait-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="personality-trait" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="natural-attribute-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="natural-attribute" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="skill-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="skill" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="relationship-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="relationship" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="gender" type="xs:string"/>
            <xs:attribute name="age" type="xs:integer"/>
            <xs:attribute name="personality-type" type="xs:string"/>
            <xs:attribute name="sponsor" type="xs:string"/>
            <xs:attribute name="country" type="xs:string"/>
            <xs:attribute name="job" type="xs:string"/>
            <xs:attribute name="favorite-main-dish" type="xs:string"/>
            <xs:attribute name="favorite-side-dish" type="xs:string"/>
            <xs:attribute name="favorite-dessert" type="xs:string"/>
            <xs:attribute name="favorite-activity" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="crew-configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="crew-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="person" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/crew/crew_alpha.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<crew-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="crew.xsd"
	name="Alpha" description="Preloaded Alpha crew">

	<!-- List of preconfigured crew  -->
	<crew-list>

		<!--    Configure a crew member   -->
		<!--    Note that it must include at least a member -->
		<!--                                                -->
		<!--             name : the person's name (required) -->
		<!--           gender : the person's gender, "male" or "female" (required)-->
		<!--              age : the person's age (optional) -->		
		<!-- personality-type : the person's MBTI personality type. (optional) -->
		<!--          country : the nationality of this person (optional. "United States" by default)  	-->
		<!--              job : the person's permanent job. (optional) -->
		<!--          sponsor : the person's Sponsor; if not defined then the 
		                        Settlement sponsor is used. (optional) -->
			
		<!-- favorite-main-dish : the person's favorite main dish. (optional)	-->
		<!-- favorite-side-dish : the person's favorite side dish. (optional)	-->
		<!--   favorite-dessert : the person's favorite dessert. (optional)		-->
		<!--  favorite-activity : the person's favorite hobby.					-->
		
		<!--    See a list of meal names in meals.xml -->
		<!--    See a list of favorite activities in FavoriteType class 		-->
		<!-- 																	-->
		<!--  Available dessert are soymilk, sugarcane juice, strawberry, granola bar, blueberry muffin, and cranberry juice -->
	
		<person name="Karen Andersen" 
			gender="female" 
			age="37"
			personality-type="ISTJ"
			country="United States"
			job="Botanist"
			favorite-main-dish="Bean Sprout Garlic Stir Fry"
			favorite-side-dish="Roasted Carrot Soup"
			favorite-dessert="strawberry"
			favorite-activity="Field Work">

			<!-- A list of predefined personality traits (optional)

		 	Personality Trait Model / Big Five Model:

//          Openness - The willingness to make a shift of standards in new situations and appreciation for a variety of experience.
// Conscientiousness - Planning ahead rather than being spontaneous.
//      Extraversion - The willingness to communicate and socialize with people. Being energetic with people.
//     Agreeableness - The adaptiveness to other people. Adopt goals in favor of others.
//       Neuroticism - The extent to which one's emotion are sensitive to his environment; 
//                     The degree of worrying or feeling vulnerable;
//	                   The emotional sensitivity and sense of security to the situation.

			See https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/personality-insights/models.shtml -->

			<personality-trait-list>
				<!-- the personality trait for a person using The Big Five Personality Traits, aka the Five Factor Model (FFM) -->
				<!--  name : the dimension (required) -->
				<!-- value : 0 (the absence of this trait) to 100 (the max presence of this trait) (required) -->
				<personality-trait name = "openness" 	value = "25"/>
				<personality-trait name = "conscientiousness"	 value = "65"/>
				<personality-trait name = "extraversion" 	value = "20"/>
				<personality-trait name = "agreeableness" 	value = "45"/>
				<personality-trait name = "neuroticism" 	value = "55"/>
			</personality-trait-list>

			<!-- List of configured natural attributes. (optional) -->
			<natural-attribute-list>
				<!-- A natural attribute for the person. -->
				<!-- name: the name of the attribute (required).-->
				<!-- value: 0 (low) to 100 (high) (required). -->
				<natural-attribute name="Strength" value="60"/>
				<natural-attribute name="Endurance" value="42"/>
				<natural-attribute name="Agility" value="71"/>
				<natural-attribute name="Teaching" value="65"/>
				<natural-attribute name="Academic Aptitude" value="70"/>
				<natural-attribute name="Experience Aptitude" value="35"/>
				<natural-attribute name="Stress Resilience" value="43"/>
				<natural-attribute name="Attractiveness" value="67"/>
				<natural-attribute name="Leadership" value="25"/>
				<natural-attribute name="Conversation" value="80"/>
			</natural-attribute-list>

			<!-- List of configured skills. (optional) -->
			<skill-list>
				<!-- A skill for the person. See the list in SkillType class. -->
				<!--  name : the name of the skill. (required). -->
				<!-- level : the level of the skill ( >= 0 ) (required). -->
				<skill name="Botany" level="2"/>
				<skill name="Mechanics" level="1"/>
				<skill name="EVA Operations" level="1"/>
				<skill name="Areology" level="1"/>
				<skill name="Medicine" level="1"/>
				<skill name="Cooking" level="1"/>
			</skill-list>

			<!-- List of configured relationships. (optional) -->
			<relationship-list>
				<!-- A relationship with another configured person. -->
				<!-- person-name : the name of the relationship person. (required) -->
				<!--   Note that other person must be configured on this list. -->
				<!--     opinion : this person's opinion of the relationship person. -->
				<!--                values from 0 (hate) to 100 (close friend) (required) -->
				<relationship person-name="Rik Declercq" opinion="100"/> 
			</relationship-list>
		</person>

		<person name="Rik Declercq" 
			gender="male" 
			personality-type="ESTP"
			country="United States"
			job="Areologist"
			favorite-main-dish="Salsa Potato Salad" 
			favorite-side-dish="Sesame Miso Soup" 
			favorite-dessert="Soymilk"
			favorite-activity="Operation">
			<personality-trait-list>
				<personality-trait name = "openness"	 value = "35"/>
				<personality-trait name = "conscientiousness"	 value = "60"/>
				<personality-trait name = "extraversion" 	value = "80"/>
				<personality-trait name = "agreeableness" 	value = "55"/>
				<personality-trait name = "neuroticism" 	value = "45"/>
			</personality-trait-list>
			<skill-list>
                <skill name="Piloting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Trading" level="1"/>
                <skill name="EVA Operations" level="1"/>
                <skill name="Cooking" level="2"/>
            </skill-list>
       </person>

        <person name="Leonardo DaVinci" 
        	gender="male" 
        	personality-type="INFJ"
        	sponsor="MS"
			country="United States"
        	job="Engineer"
			favorite-main-dish="Steamed Brown Rice" 
			favorite-side-dish="Roasted Carrot Soup" 
			favorite-dessert="Cranberry Juice"
			favorite-activity="Research">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "65"/>
				<personality-trait name = "conscientiousness" 	value = "80"/>
				<personality-trait name = "extraversion" 	value = "15"/>
				<personality-trait name = "agreeableness" 	value = "75"/>
				<personality-trait name = "neuroticism" 	value = "75"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Mechanics" level="1"/>
                <skill name="Areology" level="1"/>
                <skill name="Medicine" level="1"/>
                <skill name="Materials Science" level="2"/>
            </skill-list>
        </person>

        <person name="Lena LaGranda" 
        	gender="female" 
        	personality-type="ENFJ"
        	sponsor="MS"
			country="United States"
        	job="Technician"
			favorite-main-dish="Kidney Bean Fried Rice" 
			favorite-side-dish="Garlic Bread" 
			favorite-dessert="Blueberry Muffin"
			favorite-activity="Tinkering">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "70"/>
				<personality-trait name = "conscientiousness" 	value = "60"/>
				<personality-trait name = "extraversion" 	value = "85"/>
				<personality-trait name = "agreeableness" 	value = "80"/>
				<personality-trait name = "neuroticism" 	value = "35"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Piloting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Mechanics" level="2"/>
                <skill name="EVA Operations" level="1"/>
                <skill name="Materials Science" level="1"/>
            </skill-list>
        </person>

       <person name="Ray Bradbury" 
       		gender="male" 
       		age="50"
       		personality-type="INTP"
        	sponsor="MS"
			country="United States"
        	job="Doctor"
			favorite-main-dish="Veggie Sandwich" 
			favorite-side-dish="Taro Soup"
			favorite-dessert="Soymilk"
			favorite-activity="Astronomy">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "80"/>
				<personality-trait name = "conscientiousness" 	value = "90"/>
				<personality-trait name = "extraversion" 	value = "35"/>
				<personality-trait name = "agreeableness" 	value = "70"/>
				<personality-trait name = "neuroticism" 	value = "20"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Reporting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Medicine" level="2"/>
                <skill name="Astronomy" level="1"/>
                <skill name="Materials Science" level="1"/>
            </skill-list>
        </person>
        
	</crew-list>

</crew-configuration>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/crew/crew_founders.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<crew-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="crew.xsd"
		name="Founders" description="Project contributors">

	<!-- List of preconfigured crew  -->
	<crew-list>
	
		<person name="Manny Kung" 
			gender="male" 
			personality-type="ISTJ"
			country="United States"
			job="Botanist"
			favorite-main-dish="Bean Sprout Garlic Stir Fry"
			favorite-side-dish="Roasted Carrot Soup"
			favorite-dessert="strawberry"
			favorite-activity="Field Work">

			<personality-trait-list>
				<!-- the personality trait for a person using The Big Five Personality Traits, aka the Five Factor Model (FFM) -->
				<!--  name : the dimension (required) -->
				<!-- value : 0 (the absence of this trait) to 100 (the max presence of this trait) (required) -->
				<personality-trait name = "openness" 	value = "25"/>
				<personality-trait name = "conscientiousness"	 value = "65"/>
				<personality-trait name = "extraversion" 	value = "20"/>
				<personality-trait name = "agreeableness" 	value = "45"/>
				<personality-trait name = "neuroticism" 	value = "55"/>
			</personality-trait-list>

			<!-- List of configured natural attributes. (optional) -->
			<natural-attribute-list>
				<!-- A natural attribute for the person. -->
				<!-- name: the name of the attribute (required).-->
				<!-- value: 0 (low) to 100 (high) (required). -->
				<natural-attribute name="Strength" value="60"/>
				<natural-attribute name="Endurance" value="42"/>
				<natural-attribute name="Agility" value="71"/>
				<natural-attribute name="Teaching" value="65"/>
				<natural-attribute name="Academic Aptitude" value="70"/>
				<natural-attribute name="Experience Aptitude" value="35"/>
				<natural-attribute name="Stress Resilience" value="43"/>
				<natural-attribute name="Attractiveness" value="67"/>
				<natural-attribute name="Leadership" value="25"/>
				<natural-attribute name="Conversation" value="80"/>
			</natural-attribute-list>

			<!-- List of configured skills. (optional) -->
			<skill-list>
				<!-- A skill for the person. See the list in SkillType class. -->
				<!--  name : the name of the skill. (required). -->
				<!-- level : the level of the skill ( >= 0 ) (required). -->
				<skill name="Botany" level="2"/>
				<skill name="Mechanics" level="1"/>
				<skill name="EVA Operations" level="1"/>
				<skill name="Areology" level="1"/>
				<skill name="Medicine" level="1"/>
				<skill name="Cooking" level="1"/>
			</skill-list>
		</person>

		<person name="Lars Christensen" 
			gender="male" 
			personality-type="ESTP"
			country="Denmark"
			job="Areologist"
			favorite-main-dish="Salsa Potato Salad" 
			favorite-side-dish="Sesame Miso Soup" 
			favorite-dessert="Soymilk"
			favorite-activity="Operation">
			<personality-trait-list>
				<personality-trait name = "openness"	 value = "35"/>
				<personality-trait name = "conscientiousness"	 value = "60"/>
				<personality-trait name = "extraversion" 	value = "80"/>
				<personality-trait name = "agreeableness" 	value = "55"/>
				<personality-trait name = "neuroticism" 	value = "45"/>
			</personality-trait-list>
			<skill-list>
                <skill name="Piloting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Trading" level="1"/>
                <skill name="EVA Operations" level="1"/>
                <skill name="Cooking" level="2"/>
            </skill-list>
       </person>

        <person name="Scott Davis" 
        	gender="male" 
        	personality-type="INFJ"
			country="United States"
        	job="Engineer"
			favorite-main-dish="Steamed Brown Rice" 
			favorite-side-dish="Roasted Carrot Soup" 
			favorite-dessert="Cranberry Juice"
			favorite-activity="Research">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "65"/>
				<personality-trait name = "conscientiousness" 	value = "80"/>
				<personality-trait name = "extraversion" 	value = "15"/>
				<personality-trait name = "agreeableness" 	value = "75"/>
				<personality-trait name = "neuroticism" 	value = "75"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Mechanics" level="1"/>
                <skill name="Areology" level="1"/>
                <skill name="Medicine" level="1"/>
                <skill name="Materials Science" level="2"/>
            </skill-list>
        </person>

        <person name="Dennis Krenz" 
        	gender="male" 
        	personality-type="ENFJ"
			country="Germany"
        	job="Technician"
			favorite-main-dish="Kidney Bean Fried Rice" 
			favorite-side-dish="Garlic Bread" 
			favorite-dessert="Blueberry Muffin"
			favorite-activity="Tinkering">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "70"/>
				<personality-trait name = "conscientiousness" 	value = "60"/>
				<personality-trait name = "extraversion" 	value = "85"/>
				<personality-trait name = "agreeableness" 	value = "80"/>
				<personality-trait name = "neuroticism" 	value = "35"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Piloting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Mechanics" level="2"/>
                <skill name="EVA Operations" level="1"/>
                <skill name="Materials Science" level="1"/>
            </skill-list>
        </person>

       <person name="Barry Evans" 
       		gender="male" 
       		personality-type="INTP"
			country="United Kingdom"
        	job="Doctor"
			favorite-main-dish="Veggie Sandwich" 
			favorite-side-dish="Taro Soup"
			favorite-dessert="Soymilk"
			favorite-activity="Astronomy">
			<personality-trait-list>
				<personality-trait name = "openness" 	value = "80"/>
				<personality-trait name = "conscientiousness" 	value = "90"/>
				<personality-trait name = "extraversion" 	value = "35"/>
				<personality-trait name = "agreeableness" 	value = "70"/>
				<personality-trait name = "neuroticism" 	value = "20"/>
			</personality-trait-list>
            <skill-list>
                <skill name="Reporting" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Medicine" level="2"/>
                <skill name="Astronomy" level="1"/>
                <skill name="Materials Science" level="1"/>
            </skill-list>
        </person>
        
	</crew-list>

</crew-configuration>
