=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- 
		Note: 
		1. GDP, PPP, and population are in millions.
		2. GDP-growth is in percentage.
	-->
	
    <xs:element name="GDP">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="PPP">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="GDP-growth">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="population">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="last-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="first-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="gender" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="characteristics">
        <xs:complexType>
            <xs:attribute name="average-male-height" type="xs:string"/>
            <xs:attribute name="average-female-height" type="xs:string"/>
            <xs:attribute name="average-male-weight" type="xs:string"/>
            <xs:attribute name="average-female-weight" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
				<!-- Note: 
					1. Economics Data referenced from
					 https://www.worldometers.info/gdp/gdp-by-country/ 
					 https://www.investopedia.com/insights/worlds-top-economies/
					 https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)
					 https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)
					2. When choosing GDP and PPP, do not use IMF or CIA data set, 
					   use the 'World Bank' data set
					   
					 -->
				 <xs:element name="economics-data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="GDP" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="PPP" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="population" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="GDP-growth" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="characteristics" minOccurs="0" maxOccurs="1"/>
                <xs:element name="first-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="first-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="last-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="last-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_czech_republic.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="Czech Republic">
    <economics-data>
		 <GDP value="290,924"/>
		 <PPP value="525,730"/>
		 <population value="10.493986"/>
		 <GDP-growth value="2.46"/>
	</economics-data>
	
    <first-name-list>
        <first-name value="Jakub" gender="male" />
        <first-name value="Jan" gender="male" />
        <first-name value="Tomáš" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Adam" gender="male" />
        <first-name value="Matyáš" gender="male" />
        <first-name value="Filip" gender="male" />
        <first-name value="Vojtěch" gender="male" />
        <first-name value="Ondřej" gender="male" />
        <first-name value="Lukáš" gender="male" />
        
        <first-name value="Eliška" gender="female" />
        <first-name value="Tereza" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Adéla" gender="female" />
        <first-name value="Natálie" gender="female" />
        <first-name value="Sofie" gender="female" />
        <first-name value="Kristýna" gender="female" />
        <first-name value="Karolína" gender="female" />
        <first-name value="Viktorie" gender="female" />
        <first-name value="Barbora" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Czech surnames (male only) -->

        <last-name value="Dvořák" />
        <last-name value="Horák" />
        <last-name value="Kučera" />
        <last-name value="Novotný" />
        <last-name value="Novák" />
        <last-name value="Němec" />
        <last-name value="Procházka" />
        <last-name value="Svoboda" />
        <last-name value="Veselý" />
        <last-name value="Černý" />
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_taiwan.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Taiwan">
        
     <!-- https://www.investopedia.com/terms/f/four-asian-tigers.asp -->
    <economics-data>
		 <GDP value="32,756"/>
		 <PPP value="69,150"/>
		 <population value="23.937"/>
		 <GDP-growth value="2.1"/>
	</economics-data> 
		
    <!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="173" average-female-height="160"
	            average-male-weight="75.0" average-female-weight="60.9"/>
    <first-name-list>
        <!-- Derived from 
			https://kidadl.com/baby-names/inspiration/top-taiwanese-names-for-your-baby-that-youll-love -->
        <first-name value="Chai-Hao" gender="male" />
        <first-name value="Cheng-Hen" gender="male" />
        <first-name value="Chen-Tao" gender="male" />
        <first-name value="He-Huang" gender="male" />

        <first-name value="Li-Jing" gender="male" />
        <first-name value="Pin-Lin" gender="male" />
        <first-name value="Tsung-Han" gender="male" />
        <first-name value="Wei-Yin" gender="male" />
        <first-name value="Yan-Ting" gender="male" />

        <first-name value="Dao-Ming" gender="male" />
        <first-name value="Kai" gender="male" />
        <first-name value="Ti-Sai" gender="male" />
        <first-name value="Yi-Chun" gender="male" />
        <first-name value="Yi-Hsuan" gender="male" />

        <first-name value="Yu-Ting" gender="male" />
        <first-name value="Chih-Cheng" gender="male" />
        <first-name value="Chih-Ming" gender="male" />
        <first-name value="Chun-Chieh" gender="male" />
        <first-name value="Dao-Yu" gender="male" />

        <first-name value="Lei-Wei" gender="male" />
        <first-name value="Li-Jie" gender="male" />
        <first-name value="Li-Qiang" gender="male" />
        <first-name value="Xiu-Ying" gender="male" />
        <first-name value="Yung-Shu" gender="male" />
        
        <first-name value="Zhang-Wei" gender="male" />
        <first-name value="Zheng-Zong" gender="male" /> 
        <first-name value="Guang" gender="male" />
        <first-name value="Heping" gender="male" />
        <first-name value="Lujing" gender="male" />
               
        <first-name value="Qian" gender="male" />
        <first-name value="Quingda" gender="male" />
        <first-name value="Shizi" gender="male" />
        <first-name value="Shouxi" gender="male" />
        <first-name value="Yayang" gender="male" />
        
        <first-name value="Tiankong" gender="male" />
        <first-name value="Xin" gender="male" />
        <first-name value="Zhanshi" gender="male" />
        <first-name value="Zhenzheng" gender="male" />
        <first-name value="Ming-En" gender="male" />
        
       <!-- Derived from https://yen.com.gh/115826-taiwan-female-names-meanings.html -->

        <first-name value="Ah Lam" gender="female" />
        <first-name value="Akemi" gender="female" />
        <first-name value="Akina" gender="female" />
        <first-name value="Annya" gender="female" />
        <first-name value="Ayako" gender="female" />

        <first-name value="Ayame" gender="female" />
        <first-name value="Bo" gender="female" />
        <first-name value="Bai" gender="female" />
        <first-name value="Bao" gender="female" />
        <first-name value="Chun" gender="female" />

        <first-name value="Diu" gender="female" />
        <first-name value="Daruma" gender="female" />
        <first-name value="Ezume" gender="female" />
        <first-name value="Eiko" gender="female" />
        <first-name value="Eshima" gender="female" />
    
    
        <first-name value="Emiyo" gender="female" />
        <first-name value="Ena" gender="female" />
        <first-name value="Fen" gender="female" />
        <first-name value="Genji" gender="female" />
        <first-name value="Gin" gender="female" />

        <first-name value="Guan-Yin" gender="female" />
        <first-name value="Hanako" gender="female" />
        <first-name value="Hana" gender="female" />
        <first-name value="Hama" gender="female" />
        <first-name value="Hachi" gender="female" />

        <first-name value="Hayami" gender="female" />
        <first-name value="Harumi" gender="female" />
        <first-name value="Haru" gender="female" />
        <first-name value="Hanan" gender="female" />
        <first-name value="Hanami" gender="female" />

        <first-name value="Hsiai-Han" gender="female" />
        <first-name value="Hoshi" gender="female" />
        <first-name value="Hisa" gender="female" />
        <first-name value="Hiromi" gender="female" />
        <first-name value="Heiwa" gender="female" />

        <first-name value="Hui-Fang" gender="female" />
        <first-name value="Ishi" gender="female" />
        <first-name value="Jia" gender="female" />
        <first-name value="Ju" gender="female" />
        <first-name value="Jun" gender="female" />

        <first-name value="Jui Hui" gender="female" />
        <first-name value="Jui-Feng" gender="female" />
        <first-name value="Jumiya" gender="female" />
        <first-name value="Jumiya" gender="female" />
        <first-name value="Kaili" gender="female" />
        
        <first-name value="Kei" gender="female" />
        <first-name value="Kiaria" gender="female" />
        <first-name value="Kibo" gender="female" />
        <first-name value="Kiku" gender="female" />
        <first-name value="Kimi" gender="female" />

        <first-name value="Koko" gender="female" />
        <first-name value="Leiko" gender="female" />
        <first-name value="Majime" gender="female" />
        <first-name value="Manami" gender="female" />
        <first-name value="Mariko" gender="female" />
		
    </first-name-list>
    
    <last-name-list>
		<!-- https://imagerestorationcenter.com/the-most-common-last-names-in-taiwan/
		-->
		
        <last-name value="Chen" />
        <last-name value="Lin" />
        <last-name value="Huang" />
        <last-name value="Chang" />
        <last-name value="Li" />
        
        <last-name value="Wang" />
        <last-name value="Wu" />
        <last-name value="Liu" />
        
        <last-name value="Tsai" />
        <last-name value="Yang" />
        
        <last-name value="Ye" />
        <last-name value="Ting" />
        <last-name value="Sum" />
        <last-name value="So" />
        <last-name value="Yip" />

        <last-name value="Wong" />
        <last-name value="Chan" />
        <last-name value="Lee" />
        <last-name value="Tan" />

        <!-- https://en.wikipedia.org/wiki/List_of_common_Chinese_surnames -->
        <last-name value="Wang" />
        <last-name value="Li" />
        <last-name value="Zhang" />
        <last-name value="Liu" />
        <last-name value="Chen" />

        <last-name value="Yang" />
        <last-name value="Huang" />
        <last-name value="Zhao" />
        <last-name value="Wu" />
        <last-name value="Zhou" />

        <last-name value="Xu" />
        <last-name value="Sun" />
        <last-name value="Ma" />
        <last-name value="Zhu" />
        <last-name value="Hu" />

        <last-name value="Guo" />
        <last-name value="He" />
        <last-name value="Gao" />
        <last-name value="Lin" />
        <last-name value="Luo" />

        <last-name value="Zheng" />
        <last-name value="Liang" />
        <last-name value="Xie" />
        <last-name value="Song" />
        <last-name value="Tang" />

        <last-name value="Xu" />
        <last-name value="Han" />
        <last-name value="Feng" />
        <last-name value="Deng" />
        <last-name value="Cao" />

        <last-name value="Peng" />
        <last-name value="Zeng" />
        <last-name value="Xiao" />
        <last-name value="Tian" />
        <last-name value="Dong" />

        <last-name value="Yuan" />
        <last-name value="Pan" />
        <last-name value="Yu" />
        <last-name value="Jiang" />
        <last-name value="Cai" />

        <last-name value="Yu" />
        <last-name value="Tu" />
        <last-name value="Yeh" />
        <last-name value="Cheng" />
        <last-name value="Su" />

        <last-name value="Wei" />
        <last-name value="Lu" />
        <last-name value="Ding" />
        <last-name value="Ren" />
        <last-name value="Shen" />
        
        <!-- Miscs. -->
        <last-name value="Chin" />
        <last-name value="Vong" />
        <last-name value="Chu" />
        <last-name value="Eng" />
        <last-name value="Gong" />
        
        <last-name value="Yeoh" />
        <last-name value="Wan" />
        <last-name value="Yin" />
        <last-name value="Lui" />       
        <last-name value="Shi" />            
 
        <last-name value="Mao" />       
        <last-name value="Hao" />  
        <last-name value="Kwong" />       
        <last-name value="Kung" />  
        <last-name value="Shao" />        
               
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_luxembourg.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Luxembourg">
     <economics-data>
		 <GDP value="82,274.812251"/>
		 <PPP value="86,117"/>
		 <population value="0.647599"/>
		 <GDP-growth value="1.55"/>
	</economics-data>
	
    <first-name-list>
        <first-name value="Gabriel" gender="male" />
        <first-name value="Leo" gender="male" />
        <first-name value="Luca" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Tom" gender="male" />
        <first-name value="Ben" gender="male" />
        <first-name value="Fränk" gender="male" />
        <first-name value="Andy" gender="male" />
        <first-name value="Teo" gender="male" />

        <first-name value="Emma" gender="female" />
        <first-name value="Lara" gender="female" />
        <first-name value="Zoé" gender="female" />
        <first-name value="Amy" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Charlotte" gender="female" />
        <first-name value="Emily" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Luxembourgish surnames -->

        <last-name value="Hoffmann" />
        <last-name value="Klein" />
        <last-name value="Muller" />
        <last-name value="Reuter" />
        <last-name value="Schmit" />
        <last-name value="Schmitz" />
        <last-name value="Schroeder" />
        <last-name value="Thill" />
        <last-name value="Wagner" />
        <last-name value="Weber" />
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_austria.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Austria">
    <economics-data>
		 <GDP value="471,400"/>
		 <PPP value="614,312"/>
		 <population value="8.939617"/>
		 <GDP-growth value="5"/>
	</economics-data>
	
    <first-name-list>
        <first-name value="Lukas" gender="male" />
        <first-name value="Maximilian" gender="male" />
        <first-name value="Jakob" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Tobias" gender="male" />
        <first-name value="Paul" gender="male" />
        <first-name value="Jonas" gender="male" />
        <first-name value="Felix" gender="male" />
        <first-name value="Alexander" gender="male" />
        <first-name value="Elias" gender="male" />

        <first-name value="Anna" gender="female" />
        <first-name value="Hannah" gender="female" />
        <first-name value="Sophia" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Marie" gender="female" />
        <first-name value="Lena" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Sophie" gender="female" />
        <first-name value="Laura" gender="female" />
        <first-name value="Mia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Austrian surnames -->
        <last-name value="Bauer" />
        <last-name value="Gruber" />
        <last-name value="Hofer" />
        <last-name value="Huber" />
        <last-name value="Mayer" />
        <last-name value="Moser" />
        <last-name value="Muller" />
        <last-name value="Pichler" />
        <last-name value="Steiner" />
        <last-name value="Wagner" />
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_ireland.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="Ireland">
     <economics-data>
		 <GDP value="529,245"/>
		 <PPP value="645,565"/>
		 <population value="5.023109"/>
		 <GDP-growth value="11.97"/>
	</economics-data>
	<!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="179" average-female-height="164"
	            average-male-weight="89.2" average-female-weight="73.1"/>
    <first-name-list>
        <first-name value="Jack" gender="male" />
        <first-name value="James" gender="male" />
        <first-name value="Daniel" gender="male" />
        <first-name value="Conor" gender="male" />
        <first-name value="SeÃ¡n" gender="male" />
        <first-name value="Adam" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Michael" gender="male" />
        <first-name value="Charlie" gender="male" />
        <first-name value="Luke" gender="male" />

        <first-name value="Emily" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Ava" gender="female" />
        <first-name value="Sophie" gender="female" />
        <first-name value="Amelia" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Lucy" gender="female" />
        <first-name value="Grace" gender="female" />
        <first-name value="Chloe" gender="female" />
        <first-name value="Mia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Irish surnames -->

        <last-name value="Byrne" />
        <last-name value="Kelly" />
        <last-name value="Murphy" />
        <last-name value="Ryan" />
        <last-name value="Smith" />
        <last-name value="Sullivan" />
        <last-name value="O'Brien" />
        <last-name value="O'Connor" />
        <last-name value="O'Neill" />
        <last-name value="Walsh" />
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_finland.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Finland">
    <economics-data>
		 <GDP value="280,826"/>
		 <PPP value="328,004"/>
		 <population value="5.540,745"/>
		 <GDP-growth value="2.08"/>
	</economics-data>
	<!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="180" average-female-height="166"
	            average-male-weight="86.3" average-female-weight="71.0"/>
    <first-name-list>
        <first-name value="Leo" gender="male" />
        <first-name value="Elias" gender="male" />
        <first-name value="Onni" gender="male" />
        <first-name value="Eino" gender="male" />
        <first-name value="Oliver" gender="male" />
        <first-name value="Niilo" gender="male" />
        <first-name value="Väinö" gender="male" />
        <first-name value="Eetu" gender="male" />
        <first-name value="Leevi" gender="male" />
        <first-name value="Daniel" gender="male" />

        <first-name value="Emil" gender="male" />
        <first-name value="William" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Max" gender="male" />
        <first-name value="Benjamin" gender="male" />
        <first-name value="Liam" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Casper" gender="male" />
        <first-name value="Anton" gender="male" />
        <first-name value="Axel" gender="male" />

        <first-name value="Venla" gender="female" />
        <first-name value="Sofia" gender="female" />
        <first-name value="Aada" gender="female" />
        <first-name value="Aino" gender="female" />
        <first-name value="Elsa" gender="female" />
        <first-name value="Helmi" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Eevi" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Emilia" gender="female" />

        <first-name value="Louise" gender="female" />
        <first-name value="Alice" gender="female" />
        <first-name value="Chloé" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Inès" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Jeanne" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Adèle" gender="female" />
        <first-name value="Juliette" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Finnish surnames -->

        <last-name value="Heikkinen" />
        <last-name value="Hämäläinen" />
        <last-name value="Järvinen" />
        <last-name value="Korhonen" />
        <last-name value="Koskinen" />
        <last-name value="Laine" />
        <last-name value="Mäkelä" />
        <last-name value="Mäkinen" />
        <last-name value="Nieminen" />
        <last-name value="Virtanen" />
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_portugal.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Portugal">
     <economics-data>
		 <GDP value="251,945"/>
		 <PPP value="430,227"/>
		 <population value="10.270865"/>
		 <GDP-growth value="6.69"/>
	</economics-data>
    <!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="174" average-female-height="161"
	            average-male-weight="79.5" average-female-weight="65.8"/>	
    <first-name-list>
        <first-name value="João" gender="male" />
        <first-name value="Martim" gender="male" />
        <first-name value="Rodrigo" gender="male" />
        <first-name value="Santiago" gender="male" />
        <first-name value="Francisco" gender="male" />
        <first-name value="Afonso" gender="male" />
        <first-name value="Tomás" gender="male" />
        <first-name value="Miguel" gender="male" />
        <first-name value="Guilherme" gender="male" />
        <first-name value="Gabriel" gender="male" />

        <first-name value="Maria" gender="female" />
        <first-name value="Leonor" gender="female" />
        <first-name value="Matilde" gender="female" />
        <first-name value="Beatriz" gender="female" />
        <first-name value="Carolina" gender="female" />
        <first-name value="Mariana" gender="female" />
        <first-name value="Ana" gender="female" />
        <first-name value="Inês" gender="female" />
        <first-name value="Margarida" gender="female" />
        <first-name value="Sofia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Portuguese surnames -->

        <last-name value="Costa" />
        <last-name value="Ferreira" />
        <last-name value="Jesus" />
        <last-name value="Martins" />
        <last-name value="Oliveira" />
        <last-name value="Pereira" />
        <last-name value="Rodrigues" />
        <last-name value="Santos" />
        <last-name value="Silva" />
        <last-name value="Sousa" />
    </last-name-list>
</country>
