=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- 
		Note: 
		1. GDP, PPP, and population are in millions.
		2. GDP-growth is in percentage.
	-->
	
    <xs:element name="GDP">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="PPP">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="GDP-growth">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="population">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="last-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="first-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="gender" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="characteristics">
        <xs:complexType>
            <xs:attribute name="average-male-height" type="xs:string"/>
            <xs:attribute name="average-female-height" type="xs:string"/>
            <xs:attribute name="average-male-weight" type="xs:string"/>
            <xs:attribute name="average-female-weight" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
				<!-- Note: 
					1. Economics Data referenced from
					 https://www.worldometers.info/gdp/gdp-by-country/ 
					 https://www.investopedia.com/insights/worlds-top-economies/
					 https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)
					 https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)
					2. When choosing GDP and PPP, do not use IMF or CIA data set, 
					   use the 'World Bank' data set
					   
					 -->
				 <xs:element name="economics-data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="GDP" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="PPP" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="population" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="GDP-growth" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="characteristics" minOccurs="0" maxOccurs="1"/>
                <xs:element name="first-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="first-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="last-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="last-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_romania.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
            name="Romania">
     <economics-data>
		 <GDP value="301,262"/>
		 <PPP value="794,055"/>
		 <population value="19.659,267"/>
		 <GDP-growth value="4.79"/>
	</economics-data>
	
    <first-name-list>
        <first-name value="Andrei" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Alexandru" gender="male" />
        <first-name value="Gabriel" gender="male" />
        <first-name value="Mihai" gender="male" />
        <first-name value="Cristian" gender="male" />
        <first-name value="Stefan" gender="male" />
        <first-name value="Luca" gender="male" />
        <first-name value="IonuÅ£" gender="male" />
        <first-name value="Darius" gender="male" />

        <first-name value="Maria" gender="female" />
        <first-name value="Elena" gender="female" />
        <first-name value="Ioana" gender="female" />
        <first-name value="Andreea" gender="female" />
        <first-name value="Sofia" gender="female" />
        <first-name value="Alexandra" gender="female" />
        <first-name value="Antonia" gender="female" />
        <first-name value="Daria" gender="female" />
        <first-name value="Ana" gender="female" />
        <first-name value="Gabriela" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Romanian surnames -->

        <last-name value="Ciobanu" />
        <last-name value="Dumitru" />
        <last-name value="Gheorghe" />
        <last-name value="Matei" />
        <last-name value="Pop" />
        <last-name value="Popa" />
        <last-name value="Popescu" />
        <last-name value="Radu" />
        <last-name value="Stan" />
        <last-name value="Stoica" />
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_united_arab_emirates.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="United Arab Emirates">
     <economics-data>
		 <GDP value="507,535"/>
		 <PPP value="828,263"/>
		 <population value="0.009,441,129"/>
		 <GDP-growth value="7.41"/>
	</economics-data>
	<!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="173" average-female-height="160"
	            average-male-weight="84.5" average-female-weight="75.6"/>

    <first-name-list>
		<!-- https://firstnam.es/united-arab-emirates/boy -->
		
        <first-name value="Abdullah" gender="male" />
        <first-name value="Saeed" gender="male" />
        <first-name value="Salem" gender="male" />
        <first-name value="Sheikh" gender="male" />
        <first-name value="Mohamed" gender="male" />
        
        <first-name value="Abdel" gender="male" />
        <first-name value="Yousef" gender="male" />
        <first-name value="Hamad" gender="male" />
        <first-name value="Syed" gender="male" />
        <first-name value="Ahmed" gender="male" />
        
        <first-name value="Hussein" gender="male" />
        <first-name value="Ali" gender="male" />
        <first-name value="Khalifa" gender="male" />
        <first-name value="Nasser" gender="male" />
        <first-name value="Suleiman" gender="male" />
        
        <first-name value="Suhail" gender="male" />
        <first-name value="Rashid" gender="male" />
        <first-name value="Hamid" gender="male" />
        <first-name value="Younis" gender="male" />
        <first-name value="Badr" gender="male" />
        
        <first-name value="Khaled" gender="male" />
        <first-name value="Fahd" gender="male" />
        <first-name value="Majed" gender="male" />
        <first-name value="Mubarak" gender="male" />
        <first-name value="Yasser" gender="male" />
        
        <first-name value="Saif" gender="male" />
        <first-name value="Sultan" gender="male" />
        <first-name value="Fahim" gender="male" />
        <first-name value="Matar" gender="male" />
        <first-name value="Arun" gender="male" />
        
        <first-name value="Yacoub" gender="male" />
        <first-name value="Ghulam" gender="male" />
        <first-name value="Zaid" gender="male" />
        <first-name value="Bashir" gender="male" />
        <first-name value="Salim" gender="male" />
             
        <first-name value="Amjad" gender="male" />
        <first-name value="Ayman" gender="male" />
        <first-name value="Mansour" gender="male" />
        <first-name value="Marwan" gender="male" />
        <first-name value="Ravi" gender="male" />
        
        <first-name value="Ibrahim" gender="male" />
        <first-name value="Kamal" gender="male" />
        <first-name value="Talal" gender="male" />
        <first-name value="Sayed" gender="male" />
        <first-name value="Pradeep" gender="male" />
     
        <first-name value="Hassan" gender="male" />
        <first-name value="Omarn" gender="male" />
        <first-name value="Saad" gender="male" />
        <first-name value="Sherif" gender="male" />
        <first-name value="Ashraf" gender="male" />
        
        <first-name value="Raed" gender="male" />
        <first-name value="Habib" gender="male" />
        <first-name value="Mousa" gender="male" />
        <first-name value="Taleb" gender="male" />
        <first-name value="Zuhair" gender="male" />
             
        <first-name value="Osama" gender="male" />
        <first-name value="Raju" gender="male" />
        <first-name value="Salah" gender="male" />
        <first-name value="Marwan" gender="male" />
        <first-name value="Wahid" gender="male" />
        
        <first-name value="Essam" gender="male" />
        <first-name value="Paul" gender="male" />
        <first-name value="Emad" gender="male" />
        <first-name value="Nader" gender="male" />
        <first-name value="Nadeem" gender="male" />
        
        
		<!-- https://firstnam.es/united-arab-emirates/girl -->

        <first-name value="Ayesha" gender="female" />
        <first-name value="Alia" gender="female" />
        <first-name value="Fatima" gender="female" />
        <first-name value="Halima" gender="female" />
        <first-name value="Mariam" gender="female" />
     
        <first-name value="Khadija" gender="female" />
        <first-name value="Mona" gender="female" />
        <first-name value="Jamila" gender="female" />
        <first-name value="Salama" gender="female" />
        <first-name value="Amal" gender="female" />
     
        <first-name value="Samia" gender="female" />
        <first-name value="Shaheen" gender="female" />
        <first-name value="Asmaa" gender="female" />
        <first-name value="Salma" gender="female" />
        <first-name value="Laila" gender="female" />

        <first-name value="Nour" gender="female" />
        <first-name value="Afra" gender="female" />
        <first-name value="Hoda" gender="female" />
        <first-name value="Iman" gender="female" />
        <first-name value="Sana" gender="female" />
   
        <first-name value="Noor" gender="female" />
        <first-name value="Kiran" gender="female" />
        <first-name value="Latifa" gender="female" />
        <first-name value="Hanan" gender="female" />
        <first-name value="Amna" gender="female" />
  
        <first-name value="Sarah" gender="female" />
        <first-name value="Hind" gender="female" />
        <first-name value="Kholoud" gender="female" />
        <first-name value="Priya" gender="female" />
        <first-name value="Safia" gender="female" />
   
        <first-name value="Nadia" gender="female" />
        <first-name value="Wafa" gender="female" />
        <first-name value="Nawal" gender="female" />
        <first-name value="Ibtisam" gender="female" />
        <first-name value="Mirza" gender="female" />
  
    </first-name-list>
    
    <last-name-list>
        <!-- https://surnam.es/united-arab-emirates -->

        <last-name value="Ali" />
        <last-name value="Khan" />
        <last-name value="Kumar" />
        <last-name value="Saeed" />
        <last-name value="Ahmed" />
        
        <last-name value="Al-Shehhi" />
        <last-name value="Al-Zaabi" />
        <last-name value="Mohamed" />
        <last-name value="Al-Shamsi" />
        <last-name value="Rashid" />
        
   
        <last-name value="Hussain" />
        <last-name value="Allah" />
        <last-name value="Nair" />
        <last-name value="Singh" />
        <last-name value="Salim" />
        
        <last-name value="Al-Balushi" />
        <last-name value="Ibrahim" />
        <last-name value="Malik" />
        <last-name value="Mathew" />
        <last-name value="Shah" />
        
        <last-name value="Al-Mazroui" />
        <last-name value="Al-Zaheri" />
        <last-name value="Abbas" />
        <last-name value="El-Sewedy" />
        <last-name value="Shaikh" />
             
		<last-name value="Ahmad" />
        <last-name value="El-Amery" />
        <last-name value="Al-Habsi" />
        <last-name value="Al-Muhairi" />
        <last-name value="El-Kutby" />
        
        <last-name value="Al-Mazrouei" />
        <last-name value="Varghese" />
        <last-name value="El-Kaaby" />
        <last-name value="Hassan" />
        <last-name value="Hanafi" />
        
        <last-name value="Dsouza" />
        <last-name value="Al-Taniji" />
        <last-name value="Babu" />
        <last-name value="Al-Khatiri" />
        <last-name value="Raj" />
             
        <last-name value="Sharma" />
        <last-name value="Aloam" />
        <last-name value="Sultan" />
        <last-name value="Alam" />
        <last-name value="Menon" />
             
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_greece.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
 name="Greece">
     <economics-data>
		 <GDP value="219,066"/>
		 <PPP value="389,217"/>
		 <population value="10.384,971"/>
		 <GDP-growth value="5.91"/>
	</economics-data>
	
    <!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="179" average-female-height="165"
	            average-male-weight="88.1" average-female-weight="73.7"/>

    <first-name-list>
        <first-name value="Georgios" gender="male" />
        <first-name value="Ioannis" gender="male" />
        <first-name value="Konstantinos" gender="male" />
        <first-name value="Kostas" gender="male" />
        <first-name value="Dimitrios" gender="male" />
        <first-name value="Nikolaos" gender="male" />
        <first-name value="Panagiotis" gender="male" />
        <first-name value="Vasileios" gender="male" />
        <first-name value="Christos" gender="male" />
        <first-name value="Athanasios" gender="male" />
        <first-name value="Michail" gender="male" />

        <first-name value="Maria" gender="female" />
        <first-name value="Eleni" gender="female" />
        <first-name value="Aikaterini" gender="female" />
        <first-name value="Katerina" gender="female" />
        <first-name value="Vasikiki" gender="female" />
        <first-name value="Basiliki" gender="female" />
        <first-name value="Vaso" gender="female" />
        <first-name value="Sophia" gender="female" />
        <first-name value="Angeliki" gender="female" />
        <first-name value="Georgia" gender="female" />
        <first-name value="Giorgia" gender="female" />
        <first-name value="Gogo" gender="female" />
        <first-name value="Dimitra" gender="female" />
        <first-name value="Konstantina" gender="female" />
        <first-name value="Kostantina" gender="female" />
        <first-name value="Paraskevi" gender="female" />
        <first-name value="Paraskeui" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Greek surnames -->

        <last-name value="Angelopoulos" />
        <last-name value="Athanasiadis" />
        <last-name value="Dimitriadis" />
        <last-name value="Georgiou" />
        <last-name value="Nikolaidis" />
        <last-name value="Panagiotopoulos" />
        <last-name value="Papadakis" />
        <last-name value="Papadopoulos" />
        <last-name value="Petridis" />
        <last-name value="Vlachos" />
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_italy.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Italy">
     <economics-data>
		 <GDP value="2,010,430"/>
		 <PPP value="3,052,609"/>
		 <population value="59.037474"/>
		 <GDP-growth value="3.67"/>
	</economics-data>
    <!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="174" average-female-height="161"
	            average-male-weight="80.9" average-female-weight="64.8"/>	 
    <first-name-list>
        <first-name value="Francesco" gender="male" />
        <first-name value="Alessandro" gender="male" />
        <first-name value="Mattia" gender="male" />
        <first-name value="Lorenzo" gender="male" />
        <first-name value="Leonardo" gender="male" />
        <first-name value="Andrea" gender="male" />
        <first-name value="Gabriele" gender="male" />
        <first-name value="Matteo" gender="male" />
        <first-name value="Tommaso" gender="male" />
        <first-name value="Riccardo" gender="male" />

        <first-name value="Sofia" gender="female" />
        <first-name value="Aurora" gender="female" />
        <first-name value="Giulia" gender="female" />
        <first-name value="Giorgia" gender="female" />
        <first-name value="Alice" gender="female" />
        <first-name value="Martina" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Greta" gender="female" />
        <first-name value="Chiara" gender="female" />
        <first-name value="Anna" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Italian surnames -->

        <last-name value="Bianchi" />
        <last-name value="Colombo" />
        <last-name value="Esposito" />
        <last-name value="Ferrari" />
        <last-name value="Greco" />
        <last-name value="Marino" />
        <last-name value="Ricci" />
        <last-name value="Romano" />
        <last-name value="Rossi" />
        <last-name value="Russo" />
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_brazil.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
            name="Brazil">
    <economics-data>
		 <GDP value="1,920,096"/>
		 <PPP value="3,837,261"/>
		 <population value="215.313498"/>
		 <GDP-growth value="2.9"/>
	</economics-data>
	<!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="175" average-female-height="162"
	            average-male-weight="80.7" average-female-weight="70.3"/>

    <first-name-list>
        <!-- Brazil : will replace with Brazilian names -->
        <first-name value="Paulo" gender="male" />
        <first-name value="Eduardo" gender="male" />		
        <first-name value="Marcos" gender="male" />
        
        <!--http://iheartbrazil.com/brazilian-boy-names/ -->
        <first-name value="Jose" gender="male" />
        <first-name value="Joao" gender="male" />
        <first-name value="Antonio" gender="male" />
        <first-name value="Francisco" gender="male" />
        <first-name value="Carlos" gender="male" />
        <first-name value="Pedro" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Luiz" gender="male" />
                
        <first-name value="Adriano" gender="male" />
        <first-name value="Afonso" gender="male" />
        <first-name value="Alexandre" gender="male" />
        <first-name value="Andre" gender="male" />
        <first-name value="Arthur" gender="male" />
        <first-name value="Augusto" gender="male" />
        
        <first-name value="Benicio" gender="male" />
        <first-name value="Benjamim" gender="male" />
        <first-name value="Bento" gender="male" />
        <first-name value="Breno" gender="male" />
        <first-name value="Bernardo" gender="male" />
        <first-name value="Bruno" gender="male" />
        
        <first-name value="Caio" gender="male" />
        <first-name value="Carlos" gender="male" />
        <first-name value="Caua" gender="male" />
        <first-name value="Cesar" gender="male" />
        <first-name value="Cleiton" gender="male" />
        <first-name value="Claudio" gender="male" />
        <first-name value="Cristiano" gender="male" />

        <first-name value="Damiao" gender="male" />
        <first-name value="Danilo" gender="male" />
        <first-name value="Davi" gender="male" />
        <first-name value="Diego" gender="male" />
        <first-name value="Domingos" gender="male" />
        
        
        <!--http://iheartbrazil.com/brazilian-girl-names/ -->
        <first-name value="Michele" gender="female" />
        
        <first-name value="Bruna" gender="female" />
        
        <first-name value="Maria" gender="female" />
        <first-name value="Ana" gender="female" />
        <first-name value="Francisca" gender="female" />
        <first-name value="Antonia" gender="female" />
        <first-name value="Adriana" gender="female" />
        <first-name value="Juliana" gender="female" />
        <first-name value="Marcia" gender="female" />
        <first-name value="Fernanda" gender="female" />
        <first-name value="Patricia" gender="female" />
        <first-name value="Aline" gender="female" />
        
        
        <first-name value="Adriene" gender="female" />
        <first-name value="Agata" gender="female" />
        <first-name value="Alessandra" gender="female" />

        <first-name value="Amelia" gender="female" />
        <first-name value="Anita" gender="female" />
        <first-name value="Aline" gender="female" />
        <first-name value="Alzira" gender="female" />
        <first-name value="Ana" gender="female" />

        <first-name value="Analu" gender="female" />
        <first-name value="Andreia" gender="female" />
        <first-name value="Aparecida" gender="female" />
        <first-name value="Aurea" gender="female" />
        
        
        <first-name value="Beatriz" gender="female" />

        <first-name value="Belinda" gender="female" />
        <first-name value="Bethania" gender="female" />
        <first-name value="Bibiana" gender="female" />
        <first-name value="Bruna" gender="female" />
        
        <first-name value="Camila" gender="female" />

        <first-name value="Carina" gender="female" />
        <first-name value="Carla" gender="female" />
        <first-name value="Carolina" gender="female" />
        <first-name value="Cassia" gender="female" />
        <first-name value="Catarina" gender="female" />

        <first-name value="Celia" gender="female" />
        <first-name value="Cintia" gender="female" />
        <first-name value="Conceicao" gender="female" />
        <first-name value="Claudia" gender="female" />
        <first-name value="Cristiana" gender="female" />

    </first-name-list>
    <last-name-list>
        <!--http://iheartbrazil.com/brazilian-last-names/ -->
        
        <last-name value="Pontes" />
        <last-name value="Melo" />
        <last-name value="Vasconcellos" />
        
        <last-name value="Silva" />
        <last-name value="Santos" />
        <last-name value="Olveira" />
        <last-name value="Souza" />
        <last-name value="Rodrigues" />
        <last-name value="Ferreira" />
        <last-name value="Alves" />

        <last-name value="Anjos" />
        <last-name value="Assuncao" />
        <last-name value="Batista" />
        <last-name value="Santiago" />
        <last-name value="Trindade" />

        <last-name value="Graca" />
        <last-name value="Pereira" />
        <last-name value="Lima" />
        <last-name value="carvalho" />
        <last-name value="Gomes" />

        <last-name value="Costa" />
        <last-name value="Ribeiro" />
        <last-name value="Martins" />
        <last-name value="Almeida" />
        <last-name value="Lopes" />

        <last-name value="Soares" />
        <last-name value="Fernandes" />
        <last-name value="Vieira" />
        <last-name value="Barbosa" />
        <last-name value="Rocha" />

        <last-name value="Dias" />
        <last-name value="Nascimento" />
        <last-name value="Andrade" />

        <last-name value="Moreira" />
        <last-name value="Nunes" />
        <last-name value="Marques" />
        <last-name value="Machado" />
        <last-name value="Mendes" />

        <last-name value="Freitas" />
        <last-name value="Cardoso" />
        <last-name value="Ramos" />
        <last-name value="Goncalves" />
        <last-name value="Santana" />

        <last-name value="Teixeira" />
        <last-name value="Araujo" />
        <last-name value="Conceicao" />
        <last-name value="Bezerra" />
        <last-name value="Campos" />

        <last-name value="Reis" />
        <last-name value="Moraes" />
        <last-name value="Borges" />
        <last-name value="Castro" />
        <last-name value="Monteiro" />

        <last-name value="Moura" />
        <last-name value="Miranda" />
        <last-name value="Garcia" />
        <last-name value="Duarte" />
        <last-name value="Medeiros" />				
    </last-name-list>
</country>

=== bdowrick/mars-sim/Modules/mars-sim-core/src/main/resources/xml/country/country_sweden.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="Sweden">
     <economics-data>
		 <GDP value="585,939"/>
		 <PPP value="677,230"/>
		 <population value=".010,549,347"/>
		 <GDP-growth value="2.64"/>
	</economics-data>
			<!-- Taken from https://www.worlddata.info/average-bodyheight.php -->
    <characteristics average-male-height="180" average-female-height="167"
	            average-male-weight="87.1" average-female-weight="70.5"/>
    <first-name-list>

        <first-name value="William" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Liam" gender="male" />
        <first-name value="Oscar" gender="male" />
        <first-name value="Elias" gender="male" />
        <first-name value="Hugo" gender="male" />
        <first-name value="Oliver" gender="male" />
        <first-name value="Charlie" gender="male" />
        <first-name value="Axel" gender="male" />
        <first-name value="Vincent" gender="male" />

        <first-name value="Elsa" gender="female" />
        <first-name value="Alice" gender="female" />
        <first-name value="Maja" gender="female" />
        <first-name value="Saga" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Lily" gender="female" />
        <first-name value="Olivia" gender="female" />
        <first-name value="Ebba" gender="female" />
        <first-name value="Wilma" gender="female" />
        <first-name value="Julia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Swedish surnames -->

        <last-name value="Andersson" />
        <last-name value="Eriksson" />
        <last-name value="Gustafsson" />
        <last-name value="Johansson" />
        <last-name value="Karlsson" />
        <last-name value="Larsson" />
        <last-name value="Nilsson" />
        <last-name value="Olsson" />
        <last-name value="Persson" />
        <last-name value="Svensson" />

    </last-name-list>
</country>
